In [1]:
# checking system or device
import sys
import os
import platform

print("Python:", sys.version)
print("Platform:", platform.platform())

try:
    import torch
    print("PyTorch:", torch.__version__)
    print("CUDA available:", torch.cuda.is_available())

    if torch.cuda.is_available():
        print("GPU:", torch.cuda.get_device_name(0))
        print("CUDA version:", torch.version.cuda)
except Exception as e:
    print("PyTorch check failed:", e)

Python: 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]
Platform: Linux-6.6.122+-x86_64-with-glibc2.39
PyTorch: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4
CUDA version: 12.8

In [2]:
# importing project source code zip file
from google.colab import files

uploaded = files.upload()

Saving ai-customer-support-intelligence.zip to ai-customer-support-intelligence.zip

In [7]:
# extracting the zip file into folder
import zipfile
from pathlib import Path
import shutil

zip_path = "/content/ai-customer-support-intelligence.zip"
extract_root = Path("/content")

project = extract_root / "ai-customer-support-intelligence"

if project.exists():
    shutil.rmtree(project)

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(extract_root)

print("Project:", project)
print("Exists:", project.exists())

Project: /content/ai-customer-support-intelligence
Exists: False

In [8]:
# changing directory
%cd /content/ai-customer-support-intelligence

import os
print("Current directory:", os.getcwd())

/content/ai-customer-support-intelligence
Current directory: /content/ai-customer-support-intelligence

In [9]:
from pathlib import Path
import shutil

src_dashboard = Path("src/dashboard")

if src_dashboard.exists():
    shutil.rmtree(src_dashboard)

print("src/dashboard exists:", src_dashboard.exists())
print("dashboard/app.py exists:", Path("dashboard/app.py").exists())

src/dashboard exists: False
dashboard/app.py exists: True

In [10]:
!pip install -q --upgrade pip

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 4.6 MB/s eta 0:00:00

In [11]:
!pip install -q -r requirements.txt

In [12]:
packages = [
    "numpy",
    "pandas",
    "sklearn",
    "joblib",
    "yaml",
    "torch",
    "transformers",
    "datasets",
    "sentence_transformers",
    "faiss",
    "fitz",
    "fastapi",
    "uvicorn",
    "streamlit",
    "sqlalchemy",
    "pytest",
]

for package in packages:
    try:
        module = __import__(package)
        version = getattr(module, "__version__", "installed")
        print(f"✓ {package}: {version}")
    except Exception as e:
        print(f"✗ {package}: {e}")

✓ numpy: 2.1.3
✓ pandas: 2.2.3
✓ sklearn: 1.6.1
✓ joblib: 1.6.0
✓ yaml: 6.0.3
✓ torch: 2.11.0+cu128
✓ transformers: 5.16.1
✓ datasets: 4.8.5
✓ sentence_transformers: 5.7.0
✓ faiss: 1.15.1
warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.
✓ fitz: 1.28.2
✓ fastapi: 0.141.1
✓ uvicorn: 0.52.4
✓ streamlit: 1.64.0
✓ sqlalchemy: 2.0.52
✓ pytest: 8.4.2

In [13]:
# Compiling all files in project to check syntax error
import compileall

success = compileall.compile_dir(
    ".",
    quiet=1,
    maxlevels=20
)

print("Compilation successful:", success)

Compilation successful: True

In [14]:
# Testing — imports matching the actual project

from src.config import get_settings

from src.preprocessing.text_preprocessor import TextPreprocessor
from src.nlp.preprocessor import TextPreprocessor as NLPTextPreprocessor

from src.models.classical import ClassicalIntentClassifier
from src.models.transformer import TransformerIntentClassifier

from src.embeddings.embedder import SentenceEmbeddingModel
from src.sentiment.analyzer import SentimentAnalyzer

from src.entities.extractor import extract_entities

from src.knowledge.loader import KnowledgeLoader
from src.knowledge.chunker import DocumentChunker

from src.retrieval.vector_store import FAISSVectorStore
from src.retrieval.retriever import Retriever

from src.rag.pipeline import RAGPipeline
from src.rag.prompt_builder import build_context, build_sources
from src.rag.verifier import assess_confidence, should_escalate

from src.intelligence.priority import determine_priority
from src.intelligence.routing import route_department

from src.database.connection import init_db, get_session
from src.database.repository import TicketRepository

from src.services.support_service import SupportService

from src.api.main import app

print("✅ ALL VERIFIED IMPORTS PASSED")

✅ ALL VERIFIED IMPORTS PASSED

In [15]:
# Testing Configuration + Text Preprocessing Test

from src.config import get_settings
from src.preprocessing.text_preprocessor import TextPreprocessor

# Load project configuration
settings = get_settings()

print("===== CONFIGURATION =====")
print("Settings loaded successfully ✅")
print("\nAvailable settings:")

# Show the actual fields defined by the project's Settings class
if hasattr(settings, "model_dump"):
    print(settings.model_dump())
else:
    print(vars(settings))

print("\n===== PREPROCESSING =====")

preprocessor = TextPreprocessor()

sample_text = """
Hello, I made a payment of $250 yesterday, but my transaction is still pending.
Please help me resolve this issue.
"""

classical_text = preprocessor.preprocess_for_classical_ml(sample_text)
transformer_text = preprocessor.preprocess_for_transformer(sample_text)
clean_text = preprocessor.clean(sample_text)

print("Original:")
print(sample_text)

print("\nClassical ML:")
print(classical_text)

print("\nTransformer:")
print(transformer_text)

print("\nClean:")
print(clean_text)

# Validation
assert isinstance(classical_text, str)
assert isinstance(transformer_text, str)
assert isinstance(clean_text, str)

assert len(classical_text) > 0
assert len(transformer_text) > 0
assert len(clean_text) > 0

print("\n✅ CELL PASSED — Configuration and preprocessing working")

===== CONFIGURATION =====
Settings loaded successfully ✅

Available settings:
{'app': {'name': 'AI Customer Support Intelligence Platform', 'version': '1.0.0', 'environment': 'development', 'log_level': 'INFO'}, 'database': {'url': 'sqlite:///./artifacts/support_intelligence.db', 'echo_sql': False}, 'nlp': {'lowercase': True, 'strip_html': True, 'remove_special_chars': False, 'remove_stopwords': False, 'lemmatize': False}, 'models': {'default_classifier': 'classical', 'intent_classes': ['account_access', 'billing_and_payments', 'cancellation_and_refund', 'order_tracking', 'technical_support', 'general_inquiry'], 'urgency_levels': ['low', 'medium', 'high', 'critical'], 'classical': {'model_type': 'logistic_regression', 'max_features': 10000, 'ngram_range': [1, 2], 'min_df': 1, 'max_df': 0.98, 'c_regularization': 1.0, 'artifact_path': 'models/tfidf/classical_pipeline.joblib'}, 'transformer': {'model_name': 'distilbert-base-uncased', 'max_length': 128, 'batch_size': 8, 'learning_rate': 2e-05, 'epochs': 3, 'weight_decay': 0.01, 'warmup_ratio': 0.1, 'patience': 2, 'artifact_path': 'models/bert/intent_classifier'}}, 'sentiment': {'model_name': 'cardiffnlp/twitter-roberta-base-sentiment-latest'}, 'rag': {'knowledge_base_dir': 'data/knowledge_base', 'chunk_size': 800, 'chunk_overlap': 120, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'top_k': 3, 'similarity_threshold': 0.55, 'index_path': 'models/embeddings/faiss.index', 'metadata_path': 'models/embeddings/metadata.json'}, 'llm': {'provider': 'mock', 'model_name': 'gemini-2.5-flash', 'temperature': 0.2, 'max_output_tokens': 512, 'mock_responses_in_test': True}, 'intelligence': {'confidence_threshold': 0.6, 'high_priority_sentiments': ['negative'], 'financial_intents': ['billing_and_payments', 'cancellation_and_refund'], 'critical_intents': ['account_access', 'technical_support'], 'escalation_similarity_threshold': 0.55}, 'api': {'host': '0.0.0.0', 'port': 8000}, 'dashboard': {'port': 8501}}

===== PREPROCESSING =====
Original:

Hello, I made a payment of $250 yesterday, but my transaction is still pending.
Please help me resolve this issue.


Classical ML:
hello, i made a payment of $250 yesterday, but my transaction is still pending. please help me resolve this issue.

Transformer:
Hello, I made a payment of $250 yesterday, but my transaction is still pending. Please help me resolve this issue.

Clean:
hello, i made a payment of $250 yesterday, but my transaction is still pending. please help me resolve this issue.

✅ CELL PASSED — Configuration and preprocessing working

In [16]:
# Checking Training Data

from pathlib import Path

PROJECT_ROOT = Path("/content/ai-customer-support-intelligence")

print("===== PROJECT =====")
print("Project exists:", PROJECT_ROOT.exists())
print("Project path:", PROJECT_ROOT)

assert PROJECT_ROOT.exists(), "Project root not found"

print("\n===== DATA DIRECTORY =====")

data_dir = PROJECT_ROOT / "data"
print("Data directory exists:", data_dir.exists())

if data_dir.exists():
    for path in sorted(data_dir.rglob("*")):
        if path.is_file():
            print(path.relative_to(PROJECT_ROOT))

print("\n===== CONFIG FILES =====")

for path in sorted((PROJECT_ROOT / "configs").glob("*")):
    print(path.relative_to(PROJECT_ROOT))

print("\n✅ CELL PASSED — Project data/config structure checked")

===== PROJECT =====
Project exists: True
Project path: /content/ai-customer-support-intelligence

===== DATA DIRECTORY =====
Data directory exists: True
data/knowledge_base/account_security.md
data/knowledge_base/billing_and_invoices.md
data/knowledge_base/cancellation_and_refunds.md
data/knowledge_base/faqs.jsonl
data/knowledge_base/shipping_and_delivery.md
data/processed/.gitkeep
data/processed/test.jsonl
data/processed/train.jsonl
data/processed/val.jsonl
data/raw/README.md
data/raw/sample_tickets.jsonl
data/raw/tickets.jsonl
data/sample_queries.json

===== CONFIG FILES =====
configs/config.yaml
configs/dataset.yaml
configs/logging_config.yaml

✅ CELL PASSED — Project data/config structure checked

In [17]:
# Checking Banking77 Dataset

from datasets import load_dataset

print("===== BANKING77 DATASET =====")

dataset = load_dataset("mteb/banking77")

print("\nDataset loaded successfully ✅")

print("\nSplits:")
for split in dataset:
    print(f"{split}: {len(dataset[split])} samples")

print("\nColumns:")
print(dataset["train"].column_names)

print("\nSample:")
print(dataset["train"][0])

# Basic validation
assert "train" in dataset
assert "test" in dataset
assert len(dataset["train"]) > 0
assert len(dataset["test"]) > 0
assert "text" in dataset["train"].column_names
assert "label" in dataset["train"].column_names

print("\n✅ CELL PASSED — Banking77 dataset loaded successfully")

===== BANKING77 DATASET =====

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/16.6k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  294kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 91.4kB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/9993 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3076 [00:00<?, ? examples/s]

Dataset loaded successfully ✅

Splits:
train: 9993 samples
test: 3076 samples

Columns:
['text', 'label', 'label_text']

Sample:
{'text': 'I am still waiting on my card?', 'label': 11, 'label_text': 'card_arrival'}

✅ CELL PASSED — Banking77 dataset loaded successfully

In [18]:
# Verifying Processed Training Dataset

from pathlib import Path
import json

PROJECT_ROOT = Path("/content/ai-customer-support-intelligence")
DATA_DIR = PROJECT_ROOT / "data" / "processed"

print("===== PROCESSED DATASET =====")

for split in ["train", "val", "test"]:
    path = DATA_DIR / f"{split}.jsonl"

    print(f"\n{split.upper()}")
    print("Path:", path)
    print("Exists:", path.exists())

    assert path.exists(), f"{split}.jsonl not found"

    with open(path, "r", encoding="utf-8") as f:
        rows = [json.loads(line) for line in f if line.strip()]

    print("Samples:", len(rows))

    assert len(rows) > 0

    if rows:
        print("Columns:", list(rows[0].keys()))
        print("First sample:", rows[0])

        assert "text" in rows[0]
        assert "intent" in rows[0]

print("\n✅ CELL PASSED — Processed dataset is valid")

===== PROCESSED DATASET =====

TRAIN
Path: /content/ai-customer-support-intelligence/data/processed/train.jsonl
Exists: True
Samples: 66
Columns: ['text', 'intent']
First sample: {'text': 'Can I pick up my parcel directly at the local delivery depot instead of home delivery?', 'intent': 'order_tracking'}

VAL
Path: /content/ai-customer-support-intelligence/data/processed/val.jsonl
Exists: True
Samples: 10
Columns: ['text', 'intent']
First sample: {'text': 'I am dissatisfied with the product performance and request a full refund within 30 days.', 'intent': 'cancellation_and_refund'}

TEST
Path: /content/ai-customer-support-intelligence/data/processed/test.jsonl
Exists: True
Samples: 20
Columns: ['text', 'intent']
First sample: {'text': "Unable to log in, the screen says 'Account suspended due to too many failed password attempts'.", 'intent': 'account_access'}

✅ CELL PASSED — Processed dataset is valid

In [19]:
# Training Classical NLP Model

from pathlib import Path
import inspect

from src.models.train_classical import train

print("===== CLASSICAL MODEL TRAINING =====")

# Inspect the actual training function first
print("Training function:")
print(inspect.signature(train))

print("\nStarting training...")

# Run the project's actual training function
train()

print("\n===== CHECK MODEL ARTIFACTS =====")

PROJECT_ROOT = Path("/content/ai-customer-support-intelligence")

for path in sorted((PROJECT_ROOT / "models").rglob("*")):
    if path.is_file():
        print(path.relative_to(PROJECT_ROOT))

print("\n✅ CELL COMPLETED — Classical model training function executed")

===== CLASSICAL MODEL TRAINING =====
Training function:
(source=None)

Starting training...

===== CHECK MODEL ARTIFACTS =====
models/bert/.gitkeep
models/bert/intent_classifier/config.json
models/bert/intent_classifier/tokenizer.json
models/bert/intent_classifier/tokenizer_config.json
models/bert/intent_classifier/training_args.bin
models/embeddings/.gitkeep
models/embeddings/faiss.index
models/embeddings/metadata.json
models/sentiment/.gitkeep
models/tfidf/.gitkeep
models/tfidf/classical_pipeline.joblib

✅ CELL COMPLETED — Classical model training function executed

In [20]:
# Training Classical TF-IDF + Logistic Regression

from src.models.train_classical import train

print("===== CLASSICAL MODEL TRAINING =====")

model, evaluation = train(source="local")

print("\n===== TRAINING COMPLETED =====")

print("\nGlobal Metrics:")
print(evaluation["global_metrics"])

print("\nModel Classes:")
print(model.classes)

print("\nModel Metadata:")
print(model.get_metadata())


print("\nModel Artifact:")
print("models/tfidf/classical_pipeline.joblib")

print("\nEvaluation Report:")
print("artifacts/evaluation_reports/classical_model_report.json")

print("\n✅ CELL PASSED — Classical model trained, saved, and evaluated")

===== CLASSICAL MODEL TRAINING =====

===== TRAINING COMPLETED =====

Global Metrics:
{'accuracy': 0.8, 'precision_macro': 0.85, 'recall_macro': 0.7917, 'macro_f1': 0.7762, 'weighted_f1': 0.7861, 'per_class': {'account_access': {'precision': 0.75, 'recall': 1.0, 'f1-score': 0.8571, 'support': 3.0}, 'billing_and_payments': {'precision': 1.0, 'recall': 0.3333, 'f1-score': 0.5, 'support': 3.0}, 'cancellation_and_refund': {'precision': 0.6, 'recall': 1.0, 'f1-score': 0.75, 'support': 3.0}, 'general_inquiry': {'precision': 0.75, 'recall': 0.75, 'f1-score': 0.75, 'support': 4.0}, 'order_tracking': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 4.0}, 'technical_support': {'precision': 1.0, 'recall': 0.6667, 'f1-score': 0.8, 'support': 3.0}}, 'confusion_matrix': [[3, 0, 0, 0, 0, 0], [0, 1, 2, 0, 0, 0], [0, 0, 3, 0, 0, 0], [1, 0, 0, 3, 0, 0], [0, 0, 0, 0, 4, 0], [0, 0, 0, 1, 0, 2]], 'labels': [np.str_('account_access'), np.str_('billing_and_payments'), np.str_('cancellation_and_refund'), np.str_('general_inquiry'), np.str_('order_tracking'), np.str_('technical_support')]}

Model Classes:
[np.str_('account_access'), np.str_('billing_and_payments'), np.str_('cancellation_and_refund'), np.str_('general_inquiry'), np.str_('order_tracking'), np.str_('technical_support')]

Model Metadata:
{'model_type': 'tfidf_logistic_regression', 'classes': [np.str_('account_access'), np.str_('billing_and_payments'), np.str_('cancellation_and_refund'), np.str_('general_inquiry'), np.str_('order_tracking'), np.str_('technical_support')], 'vocabulary_size': 1108, 'ngram_range': [1, 2]}

Model Artifact:
models/tfidf/classical_pipeline.joblib

Evaluation Report:
artifacts/evaluation_reports/classical_model_report.json

✅ CELL PASSED — Classical model trained, saved, and evaluated

In [21]:
# Verifying saved Classical model can be loaded

from pathlib import Path
from src.models.classical import ClassicalIntentClassifier

model_path = Path("models/tfidf/classical_pipeline.joblib")

print("===== SAVED MODEL LOAD TEST =====")
print("Model exists:", model_path.exists())
print("Model size:", model_path.stat().st_size, "bytes")

assert model_path.exists(), "Classical model artifact was not created."
assert model_path.stat().st_size > 0, "Classical model artifact is empty."

loaded_model = ClassicalIntentClassifier.load(str(model_path))

test_messages = [
    "I cannot log into my account",
    "Where is my order?",
    "I want to cancel my order",
    "My payment is still pending",
]

print("\n===== PREDICTIONS =====")

for message in test_messages:
    prediction = loaded_model.predict_one(message)

    print(f"\nMessage: {message}")
    print("Prediction:", prediction)

print("\nLoaded model classes:")
print(loaded_model.classes)

print("\n✅ CELL PASSED — Saved Classical model loads and predicts correctly")

===== SAVED MODEL LOAD TEST =====
Model exists: True
Model size: 99325 bytes

===== PREDICTIONS =====

Message: I cannot log into my account
Prediction: {'intent': np.str_('account_access'), 'confidence': 0.3098059387544794}

Message: Where is my order?
Prediction: {'intent': np.str_('account_access'), 'confidence': 0.18440625944720485}

Message: I want to cancel my order
Prediction: {'intent': np.str_('cancellation_and_refund'), 'confidence': 0.29218956282626773}

Message: My payment is still pending
Prediction: {'intent': np.str_('billing_and_payments'), 'confidence': 0.2266620603689237}

Loaded model classes:
[np.str_('account_access'), np.str_('billing_and_payments'), np.str_('cancellation_and_refund'), np.str_('general_inquiry'), np.str_('order_tracking'), np.str_('technical_support')]

✅ CELL PASSED — Saved Classical model loads and predicts correctly

In [22]:
# Inspecting Transformer/BERT configuration

from src.config import get_settings

settings = get_settings()

print("===== TRANSFORMER CONFIGURATION =====")

transformer_config = settings.models.transformer

print("Model name:", transformer_config.model_name)
print("Max length:", transformer_config.max_length)
print("Learning rate:", transformer_config.learning_rate)
print("Epochs:", transformer_config.epochs)
print("Batch size:", transformer_config.batch_size)
print("Weight decay:", transformer_config.weight_decay)

print("\nArtifact path:", transformer_config.artifact_path)


print("\n✅ CELL PASSED — Transformer configuration verified")

===== TRANSFORMER CONFIGURATION =====
Model name: distilbert-base-uncased
Max length: 128
Learning rate: 2e-05
Epochs: 3
Batch size: 8
Weight decay: 0.01

Artifact path: models/bert/intent_classifier

✅ CELL PASSED — Transformer configuration verified

In [23]:
# Verifying DistilBERT tokenizer and model loading

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from src.config import get_settings

settings = get_settings()
model_name = settings.models.transformer.model_name
num_labels = len(settings.models.intent_classes)

print("===== DISTILBERT LOAD TEST =====")
print("Model:", model_name)
print("Number of intent classes:", num_labels)

print("\nLoading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(model_name)

print("Loading sequence classification model...")
transformer_model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels
)

print("\nTokenizer loaded:", type(tokenizer).__name__)
print("Model loaded:", type(transformer_model).__name__)
print("Model labels:", transformer_model.config.num_labels)

sample = "I cannot access my account"

encoded = tokenizer(
    sample,
    truncation=True,
    padding="max_length",
    max_length=settings.models.transformer.max_length,
    return_tensors="pt",
)

print("\nSample tokenized successfully")
print("Input shape:", tuple(encoded["input_ids"].shape))

assert transformer_model.config.num_labels == num_labels
assert encoded["input_ids"].shape[1] == settings.models.transformer.max_length

print("\n✅ CELL PASSED — DistilBERT tokenizer and model are ready")

===== DISTILBERT LOAD TEST =====
Model: distilbert-base-uncased
Number of intent classes: 6

Loading tokenizer...

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Loading sequence classification model...

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Tokenizer loaded: BertTokenizer
Model loaded: DistilBertForSequenceClassification
Model labels: 6

Sample tokenized successfully
Input shape: (1, 128)

✅ CELL PASSED — DistilBERT tokenizer and model are ready

In [24]:
# Verifying Transformer training dataset

from pathlib import Path
import json
from collections import Counter

from src.config import get_settings

settings = get_settings()

print("===== TRANSFORMER TRAINING DATA =====")

data_dir = Path("data/processed")

for split in ["train", "val", "test"]:
    path = data_dir / f"{split}.jsonl"

    print(f"\n{split.upper()}:")
    print("Path:", path)
    print("Exists:", path.exists())

    assert path.exists(), f"Missing dataset: {path}"

    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))

    print("Samples:", len(rows))
    print("Fields:", list(rows[0].keys()))

    intents = [row["intent"] for row in rows]
    print("Intent distribution:", dict(Counter(intents)))

    for row in rows[:2]:
        print("Example:", row["text"], "→", row["intent"])

    assert all("text" in row and "intent" in row for row in rows)

print("\n===== EXPECTED INTENTS =====")
print(settings.models.intent_classes)

print("\n===== DATASET INTENTS =====")
all_intents = set()

for split in ["train", "val", "test"]:
    with (data_dir / f"{split}.jsonl").open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                all_intents.add(json.loads(line)["intent"])

print(sorted(all_intents))

assert all_intents == set(settings.models.intent_classes)

print("\n✅ CELL PASSED — Transformer dataset and intent labels verified")

===== TRANSFORMER TRAINING DATA =====

TRAIN:
Path: data/processed/train.jsonl
Exists: True
Samples: 66
Fields: ['text', 'intent']
Intent distribution: {'order_tracking': 11, 'billing_and_payments': 11, 'cancellation_and_refund': 11, 'technical_support': 11, 'account_access': 11, 'general_inquiry': 11}
Example: Can I pick up my parcel directly at the local delivery depot instead of home delivery? → order_tracking
Example: The shipping status has been stuck at 'Label Created' for 5 days without carrier movement. → order_tracking

VAL:
Path: data/processed/val.jsonl
Exists: True
Samples: 10
Fields: ['text', 'intent']
Intent distribution: {'cancellation_and_refund': 2, 'billing_and_payments': 2, 'general_inquiry': 1, 'order_tracking': 1, 'technical_support': 2, 'account_access': 2}
Example: I am dissatisfied with the product performance and request a full refund within 30 days. → cancellation_and_refund
Example: Can you provide a tax invoice with our official company legal name and address? → billing_and_payments

TEST:
Path: data/processed/test.jsonl
Exists: True
Samples: 20
Fields: ['text', 'intent']
Intent distribution: {'account_access': 3, 'order_tracking': 4, 'billing_and_payments': 3, 'cancellation_and_refund': 3, 'technical_support': 3, 'general_inquiry': 4}
Example: Unable to log in, the screen says 'Account suspended due to too many failed password attempts'. → account_access
Example: Estimated delivery date was yesterday but package has not arrived. → order_tracking

===== EXPECTED INTENTS =====
['account_access', 'billing_and_payments', 'cancellation_and_refund', 'order_tracking', 'technical_support', 'general_inquiry']

===== DATASET INTENTS =====
['account_access', 'billing_and_payments', 'cancellation_and_refund', 'general_inquiry', 'order_tracking', 'technical_support']

✅ CELL PASSED — Transformer dataset and intent labels verified

In [25]:
# Verifying Transformer training hardware

import torch
import transformers

print("===== TRANSFORMER TRAINING ENVIRONMENT =====")

print("PyTorch version:", torch.__version__)
print("Transformers version:", transformers.__version__)

print("\nCUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("GPU count:", torch.cuda.device_count())

    gpu_props = torch.cuda.get_device_properties(0)
    print("GPU memory:", round(gpu_props.total_memory / (1024**3), 2), "GB")
else:
    print("Training device: CPU")

print("\nRecommended device:",
      "cuda" if torch.cuda.is_available() else "cpu")

print("\n✅ CELL PASSED — Transformer training environment verified")

===== TRANSFORMER TRAINING ENVIRONMENT =====
PyTorch version: 2.11.0+cu128
Transformers version: 5.16.1

CUDA available: True
GPU: Tesla T4
GPU count: 1
GPU memory: 14.56 GB

Recommended device: cuda

✅ CELL PASSED — Transformer training environment verified

In [26]:
# Training DistilBERT Intent Classifier

from src.bert.train import train

print("===== DISTILBERT INTENT TRAINING =====")
print("Model: distilbert-base-uncased")
print("Device: CUDA (Tesla T4)")
print("Epochs: 3")
print("Batch size: 8")
print("Learning rate: 2e-5")
print()

evaluation = train()

print("\n===== TRANSFORMER TRAINING COMPLETED =====")

print("\nEvaluation:")
print(evaluation)

print("\nArtifact directory:")
print("models/bert/intent_classifier")

print("\n✅ CELL PASSED — DistilBERT trained and evaluated")

===== DISTILBERT INTENT TRAINING =====
Model: distilbert-base-uncased
Device: CUDA (Tesla T4)
Epochs: 3
Batch size: 8
Learning rate: 2e-5

Map:   0%|          | 0/9148 [00:00<?, ? examples/s]

Map:   0%|          | 0/9148 [00:00<?, ? examples/s]

Map:   0%|          | 0/1307 [00:00<?, ? examples/s]

Map:   0%|          | 0/1307 [00:00<?, ? examples/s]

Map:   0%|          | 0/2614 [00:00<?, ? examples/s]

Map:   0%|          | 0/2614 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

===== TRANSFORMER TRAINING COMPLETED =====

Evaluation:

In [27]:
# Training DistilBERT using the verified local dataset

from src.models.train_transformer import train

print("===== DISTILBERT INTENT TRAINING =====")
print("Data source: local")
print("Model: distilbert-base-uncased")
print("Device: CUDA (Tesla T4)")
print("Epochs: 3")
print("Batch size: 8")
print("Learning rate: 2e-5")
print()

evaluation = train(source="local")

print("\n===== TRANSFORMER TRAINING COMPLETED =====")

print("\nEvaluation:")
print(evaluation)

print("\nModel artifact:")
print("models/bert/intent_classifier")

print("\nEvaluation report:")
print("artifacts/evaluation_reports/transformer_model_report.json")

print("\n✅ CELL PASSED — DistilBERT trained and evaluated on local data")

===== DISTILBERT INTENT TRAINING =====
Data source: local
Model: distilbert-base-uncased
Device: CUDA (Tesla T4)
Epochs: 3
Batch size: 8
Learning rate: 2e-5

Map:   0%|          | 0/66 [00:00<?, ? examples/s]

Map:   0%|          | 0/66 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

Map:   0%|          | 0/20 [00:00<?, ? examples/s]

Map:   0%|          | 0/20 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

===== TRANSFORMER TRAINING COMPLETED =====

Evaluation:
{'accuracy': 0.3, 'precision_macro': 0.1444, 'recall_macro': 0.3333, 'macro_f1': 0.1991, 'weighted_f1': 0.1792, 'per_class': {'account_access': {'precision': 0.2, 'recall': 0.3333, 'f1-score': 0.25, 'support': 3.0}, 'billing_and_payments': {'precision': 0.3333, 'recall': 0.6667, 'f1-score': 0.4444, 'support': 3.0}, 'cancellation_and_refund': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'general_inquiry': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 4.0}, 'order_tracking': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 4.0}, 'technical_support': {'precision': 0.3333, 'recall': 1.0, 'f1-score': 0.5, 'support': 3.0}}, 'confusion_matrix': [[1, 0, 0, 0, 0, 2], [1, 2, 0, 0, 0, 0], [2, 1, 0, 0, 0, 0], [0, 1, 0, 0, 0, 3], [1, 2, 0, 0, 0, 1], [0, 0, 0, 0, 0, 3]], 'labels': ['account_access', 'billing_and_payments', 'cancellation_and_refund', 'general_inquiry', 'order_tracking', 'technical_support']}

Model artifact:
models/bert/intent_classifier

Evaluation report:
artifacts/evaluation_reports/transformer_model_report.json

✅ CELL PASSED — DistilBERT trained and evaluated on local data

In [28]:
# Testing Transformer inference
from src.models.transformer import TransformerIntentClassifier
from src.config import get_settings

settings = get_settings()

print("===== TRANSFORMER INFERENCE TEST =====")

model = TransformerIntentClassifier(
    max_length=settings.models.transformer.max_length
)

model.load(settings.models.transformer.artifact_path)

print("✅ Saved Transformer model loaded.")
print("Classes:", model.classes)

test_messages = [
    "I cannot access my account",
    "Where is my order?",
    "I want a refund for my purchase",
    "My payment is still pending",
    "The application keeps crashing",
]

for message in test_messages:
    result = model.predict_one(message)

    print(f"\nText: {message}")
    print(f"Intent: {result['intent']}")
    print(f"Confidence: {result['confidence']:.4f}")

print("\nArtifact path:", settings.models.transformer.artifact_path)
print("Model loaded:", model.model is not None)
print("Tokenizer loaded:", model.tokenizer is not None)

print("\n✅ CELL COMPLETED")

===== TRANSFORMER INFERENCE TEST =====

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

✅ Saved Transformer model loaded.
Classes: ['account_access', 'billing_and_payments', 'cancellation_and_refund', 'general_inquiry', 'order_tracking', 'technical_support']

Text: I cannot access my account
Intent: account_access
Confidence: 0.1911

Text: Where is my order?
Intent: account_access
Confidence: 0.1840

Text: I want a refund for my purchase
Intent: account_access
Confidence: 0.1838

Text: My payment is still pending
Intent: billing_and_payments
Confidence: 0.1833

Text: The application keeps crashing
Intent: technical_support
Confidence: 0.2107

Artifact path: models/bert/intent_classifier
Model loaded: True
Tokenizer loaded: True

✅ CELL COMPLETED

In [29]:
# Testing Sentiment Analysis
from src.sentiment.analyzer import SentimentAnalyzer
from src.config import get_settings

settings = get_settings()

print("===== SENTIMENT ANALYSIS TEST =====")

analyzer = SentimentAnalyzer(
    model_name=settings.sentiment.model_name
)

test_messages = [
    "Thank you, your support was excellent!",
    "My order is still pending and this is very frustrating.",
    "I would like to know when my order will arrive.",
]

for message in test_messages:
    result = analyzer.analyze(message)

    print(f"\nText: {message}")
    print("Result:", result)

print("\nConfigured sentiment model:", settings.sentiment.model_name)
print("Expected labels: positive / neutral / negative")

print("\n✅ CELL COMPLETED")

===== SENTIMENT ANALYSIS TEST =====

config.json:   0%|          | 0.00/929 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  501MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.bias   | UNEXPECTED |  |
roberta.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  501MB

model.safetensors: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Text: Thank you, your support was excellent!
Result: {'sentiment': 'positive', 'confidence': 0.9845607280731201}

Text: My order is still pending and this is very frustrating.
Result: {'sentiment': 'negative', 'confidence': 0.9218071103096008}

Text: I would like to know when my order will arrive.
Result: {'sentiment': 'neutral', 'confidence': 0.7731150984764099}

Configured sentiment model: cardiffnlp/twitter-roberta-base-sentiment-latest
Expected labels: positive / neutral / negative

✅ CELL COMPLETED

In [30]:
# Testing Entity Extraction
from src.entities.extractor import extract_entities

print("===== ENTITY EXTRACTION TEST =====")

test_messages = [
    "My order ORD-12345 is delayed and I was charged $49.99 on 12/08/2026.",
    "Please check order #987654. My email is customer@example.com.",
    "I paid ₹2499 for the product on 15-08-2026.",
    "There is a problem with my account."
]

for message in test_messages:
    result = extract_entities(message)

    print(f"\nText: {message}")
    print("Entities:", result)

print("\n✅ CELL COMPLETED")

===== ENTITY EXTRACTION TEST =====

Text: My order ORD-12345 is delayed and I was charged $49.99 on 12/08/2026.
Entities: {'order_ids': ['ORD-12345'], 'amounts': ['$49.99'], 'dates': ['12/08/2026'], 'emails': []}

Text: Please check order #987654. My email is customer@example.com.
Entities: {'order_ids': ['987654'], 'amounts': [], 'dates': [], 'emails': ['customer@example.com']}

Text: I paid ₹2499 for the product on 15-08-2026.
Entities: {'order_ids': [], 'amounts': ['₹2499'], 'dates': ['15-08-2026'], 'emails': []}

Text: There is a problem with my account.
Entities: {'order_ids': [], 'amounts': [], 'dates': [], 'emails': []}

✅ CELL COMPLETED

In [31]:
# Second time testing entity extraction
from src.entities.extractor import extract_entities

print("===== Second ENTITY EXTRACTION TEST =====")

test_messages = [
    "My order ORD-12345 is delayed and I was charged $49.99 on 12/08/2026.",
    "Please check order #987654. My email is customer@example.com.",
    "I paid ₹2499 for the product on 15-08-2026.",
    "The order number is ABC-7788 and the amount is INR 2,499.50.",
]

for message in test_messages:
    result = extract_entities(message)

    print(f"\nText: {message}")
    print("Entities:", result)

print("\n===== EXPECTED KEY RESULTS =====")
print("1. $49.99 should be captured completely")
print("2. ₹2499 should be captured completely")
print("3. INR 2,499.50 should be captured completely")
print("4. ABC-7788 should be captured as the order ID")
print("5. Existing date/email extraction should still work")

print("\n✅ CELL COMPLETED")

===== Second ENTITY EXTRACTION TEST =====

Text: My order ORD-12345 is delayed and I was charged $49.99 on 12/08/2026.
Entities: {'order_ids': ['ORD-12345'], 'amounts': ['$49.99'], 'dates': ['12/08/2026'], 'emails': []}

Text: Please check order #987654. My email is customer@example.com.
Entities: {'order_ids': ['987654'], 'amounts': [], 'dates': [], 'emails': ['customer@example.com']}

Text: I paid ₹2499 for the product on 15-08-2026.
Entities: {'order_ids': [], 'amounts': ['₹2499'], 'dates': ['15-08-2026'], 'emails': []}

Text: The order number is ABC-7788 and the amount is INR 2,499.50.
Entities: {'order_ids': ['ABC-7788'], 'amounts': ['INR 2,499.50'], 'dates': [], 'emails': []}

===== EXPECTED KEY RESULTS =====
1. $49.99 should be captured completely
2. ₹2499 should be captured completely
3. INR 2,499.50 should be captured completely
4. ABC-7788 should be captured as the order ID
5. Existing date/email extraction should still work

✅ CELL COMPLETED

In [32]:
# Testing priority engine
from src.intelligence.priority import determine_priority

print("===== PRIORITY ENGINE TEST =====")

test_cases = [
    {
        "name": "Normal inquiry",
        "intent": "general_inquiry",
        "sentiment": "neutral",
        "confidence": 0.90,
        "entities": {},
        "message": "What are your business hours?"
    },
    {
        "name": "Negative billing issue",
        "intent": "billing_and_payments",
        "sentiment": "negative",
        "confidence": 0.85,
        "entities": {"amounts": ["$499.99"]},
        "message": "I was charged incorrectly and need my money back."
    },
    {
        "name": "Account access problem",
        "intent": "account_access",
        "sentiment": "negative",
        "confidence": 0.80,
        "entities": {},
        "message": "I cannot access my account."
    },
    {
        "name": "Technical problem",
        "intent": "technical_support",
        "sentiment": "negative",
        "confidence": 0.75,
        "entities": {},
        "message": "The application keeps crashing."
    },
    {
        "name": "Low-confidence prediction",
        "intent": "general_inquiry",
        "sentiment": "neutral",
        "confidence": 0.30,
        "entities": {},
        "message": "Something is wrong with my order."
    },
]

for case in test_cases:
    priority = determine_priority(
        intent=case["intent"],
        sentiment=case["sentiment"],
        intent_confidence=case["confidence"],
        entities=case["entities"],
        message=case["message"],
    )

    print(f"\n{case['name']}")
    print(f"Intent: {case['intent']}")
    print(f"Sentiment: {case['sentiment']}")
    print(f"Confidence: {case['confidence']}")
    print(f"Priority: {priority}")

print("\n===== CONFIGURED PRIORITIES =====")
print("Confidence threshold:", 0.60)
print("High-priority sentiment:", "negative")
print("Financial intents:", ["billing_and_payments", "cancellation_and_refund"])
print("Critical intents:", ["account_access", "technical_support"])

print("\n✅ CELL COMPLETED")

===== PRIORITY ENGINE TEST =====

Normal inquiry
Intent: general_inquiry
Sentiment: neutral
Confidence: 0.9
Priority: low

Negative billing issue
Intent: billing_and_payments
Sentiment: negative
Confidence: 0.85
Priority: high

Account access problem
Intent: account_access
Sentiment: negative
Confidence: 0.8
Priority: high

Technical problem
Intent: technical_support
Sentiment: negative
Confidence: 0.75
Priority: high

Low-confidence prediction
Intent: general_inquiry
Sentiment: neutral
Confidence: 0.3
Priority: medium

===== CONFIGURED PRIORITIES =====
Confidence threshold: 0.6
High-priority sentiment: negative
Financial intents: ['billing_and_payments', 'cancellation_and_refund']
Critical intents: ['account_access', 'technical_support']

✅ CELL COMPLETED

In [33]:
# Testing Routing Engine
from src.intelligence.routing import route_department

print("===== ROUTING ENGINE TEST =====")

test_cases = [
    ("account_access", "Account access issue"),
    ("billing_and_payments", "Payment issue"),
    ("cancellation_and_refund", "Refund request"),
    ("order_tracking", "Order status"),
    ("technical_support", "Technical problem"),
    ("general_inquiry", "General question"),
    ("unknown_intent", "Unknown intent"),
]

for intent, description in test_cases:
    department = route_department(intent)

    print(f"\n{description}")
    print(f"Intent: {intent}")
    print(f"Department: {department}")

print("\n===== ROUTING TEST COMPLETED =====")
print("Routing is deterministic and intent-based.")

print("\n✅ CELL  COMPLETED")

===== ROUTING ENGINE TEST =====

Account access issue
Intent: account_access
Department: account_support

Payment issue
Intent: billing_and_payments
Department: billing

Refund request
Intent: cancellation_and_refund
Department: billing

Order status
Intent: order_tracking
Department: logistics

Technical problem
Intent: technical_support
Department: technical_support

General question
Intent: general_inquiry
Department: customer_support

Unknown intent
Intent: unknown_intent
Department: customer_support

===== ROUTING TEST COMPLETED =====
Routing is deterministic and intent-based.

✅ CELL  COMPLETED

In [34]:
# Testing Support Service Working
from src.models.classical import ClassicalIntentClassifier
from src.sentiment.analyzer import SentimentAnalyzer
from src.rag.pipeline import RAGPipeline
from src.services.support_service import SupportService

print("===== BUILDING SUPPORT SERVICE =====")

# 1. Load the trained classical intent classifier
classifier = ClassicalIntentClassifier()
classifier.load("models/tfidf/classical_pipeline.joblib")
print("✅ Classical intent classifier loaded")

# 2. Load configured sentiment model
sentiment_analyzer = SentimentAnalyzer()
print("✅ Sentiment analyzer created")

# 3. Create the retriever using the project's default configuration.
retriever = Retriever()
print("✅ Retriever created")

# RAG pipeline uses the retriever.
rag_pipeline = RAGPipeline(retriever=retriever)
print("✅ RAG pipeline created")


# 4. Assemble the complete support service
service = SupportService(
    classifier=classifier,
    sentiment_analyzer=sentiment_analyzer,
    rag_pipeline=rag_pipeline
)

print("✅ SupportService created successfully")

print("\n===== DEPENDENCY STATUS =====")
print(f"Classifier: {type(classifier).__name__}")
print(f"Sentiment: {type(sentiment_analyzer).__name__}")
print(f"RAG: {type(rag_pipeline).__name__}")

print(f"Service: {type(service).__name__}")

print("\n✅ CELL COMPLETED")

===== BUILDING SUPPORT SERVICE =====
✅ Classical intent classifier loaded
✅ Sentiment analyzer created
✅ Retriever created
✅ RAG pipeline created
✅ SupportService created successfully

===== DEPENDENCY STATUS =====
Classifier: ClassicalIntentClassifier
Sentiment: SentimentAnalyzer
RAG: RAGPipeline
Service: SupportService

✅ CELL COMPLETED

In [35]:
# loading the fitted classifier from models directory
from src.models.classical import ClassicalIntentClassifier

print("===== CORRECTING CLASSIFIER LOAD =====")

# load() returns the fitted classifier object.
classifier = ClassicalIntentClassifier.load(
    "models/tfidf/classical_pipeline.joblib"
)

print("Classifier type:", type(classifier).__name__)
print("Internal classifier:", type(classifier.classifier).__name__)
print("Vectorizer:", type(classifier.vectorizer).__name__)
print("Classes:", classifier.classes)

# Verify that prediction now works.
test_prediction = classifier.predict_one(
    "I cannot access my account"
)

print("\nTest prediction:", test_prediction)

print("\n✅ CELL  COMPLETED")

===== CORRECTING CLASSIFIER LOAD =====
Classifier type: ClassicalIntentClassifier
Internal classifier: LogisticRegression
Vectorizer: TfidfVectorizer
Classes: [np.str_('account_access'), np.str_('billing_and_payments'), np.str_('cancellation_and_refund'), np.str_('general_inquiry'), np.str_('order_tracking'), np.str_('technical_support')]

Test prediction: {'intent': np.str_('account_access'), 'confidence': 0.311221247315239}

✅ CELL  COMPLETED

In [36]:
# Rebuilding the complete support and service and testing one more time
from src.services.support_service import SupportService

print("===== REBUILDING COMPLETE SUPPORT SERVICE =====")

service = SupportService(
    classifier=classifier,
    sentiment_analyzer=sentiment_analyzer,
    rag_pipeline=rag_pipeline
)

print("✅ SupportService rebuilt with fitted classifier")

print("\n===== END-TO-END NLP INTELLIGENCE TEST =====")

test_messages = [
    "I cannot access my account and I am really frustrated.",
    "I was charged $499.99 incorrectly and want a refund.",
    "Where is my order #ABC-7788?",
    "The application keeps crashing whenever I try to login.",
    "Can you tell me your business hours?",
]

for i, message in enumerate(test_messages, 1):
    print(f"\n{'=' * 70}")
    print(f"CASE {i}")
    print(f"Message: {message}")

    try:
        result = service.analyze(message)

        print(f"Intent: {result.get('intent')}")
        print(f"Intent confidence: {result.get('intent_confidence')}")
        print(f"Sentiment: {result.get('sentiment')}")
        print(f"Entities: {result.get('entities')}")
        print(f"Priority: {result.get('priority')}")
        print(f"Department: {result.get('department')}")

    except Exception as e:
        print(f"❌ ERROR: {type(e).__name__}: {e}")

print(f"\n{'=' * 70}")
print("===== END-TO-END TEST FINISHED =====")
print("\n✅ CELL COMPLETED")

===== REBUILDING COMPLETE SUPPORT SERVICE =====
✅ SupportService rebuilt with fitted classifier

===== END-TO-END NLP INTELLIGENCE TEST =====

======================================================================
CASE 1
Message: I cannot access my account and I am really frustrated.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Intent: account_access
Intent confidence: 0.3124
Sentiment: negative
Entities: {'order_ids': [], 'amounts': [], 'dates': [], 'emails': []}
Priority: high
Department: account_support

======================================================================
CASE 2
Message: I was charged $499.99 incorrectly and want a refund.
Intent: cancellation_and_refund
Intent confidence: 0.2371
Sentiment: negative
Entities: {'order_ids': [], 'amounts': ['$499.99'], 'dates': [], 'emails': []}
Priority: high
Department: billing

======================================================================
CASE 3
Message: Where is my order #ABC-7788?
Intent: account_access
Intent confidence: 0.1844
Sentiment: negative
Entities: {'order_ids': ['ABC-7788'], 'amounts': [], 'dates': [], 'emails': []}
Priority: high
Department: account_support

======================================================================
CASE 4
Message: The application keeps crashing whenever I try to login.
Intent: technical_support
Intent confidence: 0.2451
Sentiment: negative
Entities: {'order_ids': [], 'amounts': [], 'dates': [], 'emails': []}
Priority: high
Department: technical_support

======================================================================
CASE 5
Message: Can you tell me your business hours?
Intent: general_inquiry
Intent confidence: 0.2333
Sentiment: negative
Entities: {'order_ids': [], 'amounts': [], 'dates': [], 'emails': []}
Priority: medium
Department: customer_support

======================================================================
===== END-TO-END TEST FINISHED =====

✅ CELL COMPLETED

In [37]:
# Testing Rag knowledge base
from pathlib import Path
from src.knowledge.loader import KnowledgeLoader
from src.knowledge.chunker import DocumentChunker

print("===== RAG KNOWLEDGE BASE TEST =====")

kb_dir = Path("data/knowledge_base")

print("Knowledge base directory:", kb_dir)
print("Exists:", kb_dir.exists())

print("\n===== FILES =====")
for file in sorted(kb_dir.iterdir()):
    if file.is_file():
        print(f"  - {file.name}")

# Load documents using the actual project API.
loader = KnowledgeLoader(str(kb_dir))
documents = loader.load()

print("\nDocuments loaded:", len(documents))

for i, doc in enumerate(documents, 1):
    print(f"\nDocument {i}:")
    print("Metadata:", doc.metadata)
    print("Text preview:", doc.text[:300].replace("\n", " "))

# Use configured chunking parameters.
chunker = DocumentChunker(
    chunk_size=800,
    chunk_overlap=120
)

chunks = chunker.chunk(documents)

print("\n===== CHUNKING =====")
print("Chunks created:", len(chunks))

if chunks:
    print("\nSample chunk:")
    print("Chunk ID:", chunks[0]["chunk_id"])
    print("Document:", chunks[0]["document"])
    print("Page:", chunks[0]["page"])
    print("Section:", chunks[0]["section"])
    print("Text:", chunks[0]["text"][:500])

print("\n===== RAG KNOWLEDGE TEST FINISHED =====")
print("\n✅ CELL COMPLETED")

===== RAG KNOWLEDGE BASE TEST =====
Knowledge base directory: data/knowledge_base
Exists: True

===== FILES =====
  - account_security.md
  - billing_and_invoices.md
  - cancellation_and_refunds.md
  - faqs.jsonl
  - shipping_and_delivery.md

Documents loaded: 28

Document 1:
Metadata: {'document': 'account_security.md', 'page': None, 'path': 'data/knowledge_base/account_security.md'}
Text preview: # Account Security and Authentication Guide  ## 1. Password Reset Procedures If you have forgotten your password or your reset link has expired: 1. Go to the login screen and click **Forgot Password**. 2. Enter your primary email address. Reset links are valid for 15 minutes for security purposes. 3

Document 2:
Metadata: {'document': 'billing_and_invoices.md', 'page': None, 'path': 'data/knowledge_base/billing_and_invoices.md'}
Text preview: # Billing and Invoicing Policies  ## 1. Duplicate Charges and Billing Disputes If your credit card or bank account shows duplicate charges for the same billing cycle: 1. Contact support immediately with your transaction receipt IDs. 2. Duplicate charges caused by payment gateway processing timeouts

Document 3:
Metadata: {'document': 'cancellation_and_refunds.md', 'page': None, 'path': 'data/knowledge_base/cancellation_and_refunds.md'}
Text preview: # Cancellation and Refund Policy  ## 1. 30-Day Money-Back Guarantee All digital subscriptions and software licenses come with a 30-day money-back guarantee. If you are unsatisfied with the product, you may request a 100% refund within 30 days of the initial purchase date.  ## 2. Prorated Refunds for

Document 4:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-01', 'category': 'cancellation_and_refund', 'line': 1}
Text preview: Question: How do I request a refund for an accidental purchase or duplicate order? Answer: You can request a full refund within 30 days of purchase under our 30-day money-back guarantee. Go to Account Settings > Billing & Subscriptions and click 'Request Refund', or submit a ticket with your transac

Document 5:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-02', 'category': 'cancellation_and_refund', 'line': 2}
Text preview: Question: Can I cancel my subscription and get a prorated refund? Answer: Annual plan subscribers can cancel anytime and receive a prorated refund for unused full calendar months, subject to a 10% administrative fee. Monthly subscriptions remain active until the end of the paid billing cycle without

Document 6:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-03', 'category': 'cancellation_and_refund', 'line': 3}
Text preview: Question: How long does it take for a refund to show up on my credit card statement? Answer: Once approved, refunds are processed immediately. Depending on your financial institution, funds typically appear on your statement within 3 to 5 business days.

Document 7:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-04', 'category': 'cancellation_and_refund', 'line': 4}
Text preview: Question: What is the return policy for damaged or defective physical products? Answer: Defective physical items must be returned within 14 calendar days of delivery with original packaging. Customer support provides a prepaid return shipping label upon photo verification of damage.

Document 8:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-05', 'category': 'account_access', 'line': 5}
Text preview: Question: How do I reset my account password if I forgot it? Answer: Click 'Forgot Password' on the login screen, enter your registered email, and a secure password reset link valid for 15 minutes will be emailed to you.

Document 9:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-06', 'category': 'account_access', 'line': 6}
Text preview: Question: What should I do if my Two-Factor Authentication 2FA code is not working? Answer: Use one of your 10 emergency backup recovery codes generated during 2FA setup. If you do not have backup codes, submit an identity verification ticket to initiate manual account recovery.

Document 10:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-07', 'category': 'account_access', 'line': 7}
Text preview: Question: Why is my account locked or suspended due to failed login attempts? Answer: For security protection, accounts are temporarily locked for 30 minutes after 5 consecutive failed login attempts. You can wait 30 minutes or click 'Forgot Password' to unlock immediately.

Document 11:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-08', 'category': 'account_access', 'line': 8}
Text preview: Question: I received an alert about a suspicious login from an unknown IP address. What should I do? Answer: Click 'This Wasn't Me' in the security alert email immediately. This will terminate all active sessions across all devices, revoke API tokens, and prompt you to set a new password.

Document 12:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-09', 'category': 'billing_and_payments', 'line': 9}
Text preview: Question: Why was my credit card charged twice for the same billing period? Answer: Duplicate charges usually result from network timeouts during checkout. The duplicate pre-authorization hold will automatically fall off your bank account within 3 to 5 business days.

Document 13:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-10', 'category': 'billing_and_payments', 'line': 10}
Text preview: Question: How do I update my credit card or payment method on file? Answer: Go to Account Settings > Billing & Invoices > Payment Methods. Click 'Add Payment Method', enter your new card details, and set it as default.

Document 14:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-11', 'category': 'billing_and_payments', 'line': 11}
Text preview: Question: Where can I download PDF copies of my paid invoices with VAT/tax details? Answer: Invoices are available under Account Settings > Invoices. Click 'Download PDF' next to any billing period. You can add your company VAT/tax ID under Billing Information before downloading.

Document 15:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-12', 'category': 'billing_and_payments', 'line': 12}
Text preview: Question: My payment failed due to insufficient funds. When will you retry charging my card? Answer: Our billing system automatically retries failed payments on Day 1, Day 4, and Day 7. A 7-day grace period is provided before subscription features are paused.

Document 16:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-13', 'category': 'order_tracking', 'line': 13}
Text preview: Question: How can I track the shipping and delivery status of my order? Answer: Once your order ships, a tracking number and courier link are emailed to you. You can also view live tracking status anytime in your account under 'Order History'.

Document 17:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-14', 'category': 'order_tracking', 'line': 14}
Text preview: Question: Why has my tracking number not updated for several days? Answer: Tracking numbers are generated when the label is printed. Carrier scans may take 24 to 48 hours to update once the carrier physically scans the parcel at the origin sorting hub.

Document 18:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-15', 'category': 'order_tracking', 'line': 15}
Text preview: Question: What should I do if tracking says delivered but I did not receive my package? Answer: First check surrounding areas and with neighbors. Couriers occasionally scan deliveries prematurely. If the parcel does not arrive within 24 hours of the delivery notification, contact support to file a c

Document 19:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-16', 'category': 'order_tracking', 'line': 16}
Text preview: Question: Can I change my shipping address or expedite shipping after placing an order? Answer: Shipping address and delivery speed can only be modified within 60 minutes of placing the order before the warehouse begins fulfillment. Contact live chat support immediately for order adjustments.

Document 20:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-17', 'category': 'technical_support', 'line': 17}
Text preview: Question: The application crashes immediately upon opening or displays a white screen. Answer: Try clearing your browser cache and cookies or restarting the desktop client. Ensure your device meets minimum system requirements and hardware acceleration is enabled.

Document 21:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-18', 'category': 'technical_support', 'line': 18}
Text preview: Question: How do I resolve API HTTP 429 Too Many Requests rate limit errors? Answer: HTTP 429 indicates you have exceeded your plan's rate limit quota. Implement exponential backoff retries in your client application or upgrade your plan for higher throughput.

Document 22:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-19', 'category': 'technical_support', 'line': 19}
Text preview: Question: Webhooks are failing or timing out when delivering payloads to our server. Answer: Ensure your webhook listener endpoint responds with an HTTP 200 OK status within 5000 milliseconds. Our servers automatically retry failed deliveries up to 5 times with exponential backoff.

Document 23:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-20', 'category': 'technical_support', 'line': 20}
Text preview: Question: CSV file upload fails with internal server error 500. Answer: Verify that your CSV file is UTF-8 encoded, under 50MB in size, and does not contain unescaped quotation marks in header rows. Download our sample CSV template from the documentation.

Document 24:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-21', 'category': 'general_inquiry', 'line': 21}
Text preview: Question: What are customer support business hours and response times? Answer: Our standard customer support operates Monday through Friday, 9:00 AM to 6:00 PM EST. Critical severity issues for enterprise tier customers receive 24/7 coverage with a 1-hour response SLA.

Document 25:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-22', 'category': 'general_inquiry', 'line': 22}
Text preview: Question: Do you offer non-profit, student, or educational discounts? Answer: Yes! Verified non-profit organizations and accredited educational institutions qualify for a 30% discount on all annual software plans upon submitting proof of status.

Document 26:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-23', 'category': 'general_inquiry', 'line': 23}
Text preview: Question: Is customer data encrypted and compliant with SOC2 and GDPR regulations? Answer: Yes. All data is encrypted in transit using TLS 1.3 and at rest using AES-256. We maintain SOC2 Type II certification and offer full GDPR-compliant Data Processing Agreements (DPAs).

Document 27:
Metadata: {'document': 'faqs.jsonl', 'page': None, 'path': 'data/knowledge_base/faqs.jsonl', 'faq_id': 'faq-24', 'category': 'general_inquiry', 'line': 24}
Text preview: Question: Does your platform support Single Sign-On (SSO) with Okta or Google Workspace? Answer: Yes, SAML 2.0 and OIDC Single Sign-On are supported for Okta, Azure Active Directory, Google Workspace, and OneLogin on Business and Enterprise plans.

Document 28:
Metadata: {'document': 'shipping_and_delivery.md', 'page': None, 'path': 'data/knowledge_base/shipping_and_delivery.md'}
Text preview: # Shipping, Tracking, and Delivery Policies  ## 1. Tracking Status Updates Carrier tracking numbers are assigned within 24 hours of order fulfillment. Tracking scans may take up to 48 hours to update once the carrier takes physical possession of the shipment.  ## 2. Missing or Stolen Packages If you

===== CHUNKING =====
Chunks created: 28

Sample chunk:
Chunk ID: account_security_md_0000
Document: account_security.md
Page: None
Section: None
Text: # Account Security and Authentication Guide ## 1. Password Reset Procedures If you have forgotten your password or your reset link has expired: 1. Go to the login screen and click **Forgot Password**. 2. Enter your primary email address. Reset links are valid for 15 minutes for security purposes. 3. If the link expires, request a fresh link. Make sure to check your spam/junk folder. ## 2. Two-Factor Authentication (2FA) Recovery If you lose access to your authenticator app or your SMS verificati

===== RAG KNOWLEDGE TEST FINISHED =====

✅ CELL COMPLETED

In [38]:
# Testing Faiss Vector Index is working or not
from pathlib import Path
from src.knowledge.loader import KnowledgeLoader
from src.knowledge.chunker import DocumentChunker
from src.retrieval.vector_store import FAISSVectorStore

print("===== BUILDING FAISS VECTOR INDEX =====")

# Load documents
loader = KnowledgeLoader("data/knowledge_base")
documents = loader.load()

# Create chunks
chunker = DocumentChunker(
    chunk_size=800,
    chunk_overlap=120
)
chunks = chunker.chunk(documents)

print("Documents:", len(documents))
print("Chunks:", len(chunks))

# Create embedding model
embedder = SentenceEmbeddingModel(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("\nEmbedding dimension:", embedder.dimension)

# Create persistent FAISS store
store = FAISSVectorStore(
    index_path="models/embeddings/faiss.index",
    metadata_path="models/embeddings/metadata.json"
)

# Build and save the index
store.build(
    chunks=chunks,
    embedder=embedder
)

print("\n===== INDEX STATUS =====")

index_path = Path("models/embeddings/faiss.index")
metadata_path = Path("models/embeddings/metadata.json")

print("FAISS index exists:", index_path.exists())
print("Metadata exists:", metadata_path.exists())
print("Vectors stored:", store.index.ntotal)
print("Vector dimension:", store.index.d)
print("Metadata records:", len(store.metadata))

print("\n===== FAISS INDEX BUILD FINISHED =====")
print("\n✅ CELL COMPLETED")

===== BUILDING FAISS VECTOR INDEX =====
Documents: 28
Chunks: 28

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding dimension: 384

===== INDEX STATUS =====
FAISS index exists: True
Metadata exists: True
Vectors stored: 28
Vector dimension: 384
Metadata records: 28

===== FAISS INDEX BUILD FINISHED =====

✅ CELL COMPLETED

/content/ai-customer-support-intelligence/src/embeddings/embedder.py:34: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  return int(self._load().get_sentence_embedding_dimension())

In [39]:
print("===== RETRIEVAL SIMILARITY DIAGNOSTIC =====")

diagnostic_queries = [
    "How can I reset my password?",
    "I was charged twice for the same payment.",
    "Can I get a refund for my subscription?",
    "Where can I track my package?",
    "What is the weather today?",
]

for query in diagnostic_queries:
    # Directly search the FAISS store with a very low threshold
    # so we can inspect scores that were previously filtered out.
    results = store.search(
        query=query,
        embedder=embedder,
        top_k=4,
        threshold=0.0
    )

    print(f"\n{'=' * 70}")
    print("QUERY:", query)

    for rank, result in enumerate(results, 1):
        print(
            f"{rank}. "
            f"{result['document']} | "
            f"similarity={result['similarity']}"
        )

print("\n===== DIAGNOSTIC FINISHED =====")
print("\nNote: This cell only measures retrieval scores.")
print("It does not modify the index or configuration.")

print("\n✅ CELL COMPLETED")

===== RETRIEVAL SIMILARITY DIAGNOSTIC =====

======================================================================
QUERY: How can I reset my password?
1. faqs.jsonl | similarity=0.7173
2. account_security.md | similarity=0.5058
3. faqs.jsonl | similarity=0.4257
4. faqs.jsonl | similarity=0.2894

======================================================================
QUERY: I was charged twice for the same payment.
1. faqs.jsonl | similarity=0.6149
2. billing_and_invoices.md | similarity=0.5301
3. faqs.jsonl | similarity=0.432
4. faqs.jsonl | similarity=0.4058

======================================================================
QUERY: Can I get a refund for my subscription?
1. cancellation_and_refunds.md | similarity=0.6682
2. faqs.jsonl | similarity=0.6389
3. faqs.jsonl | similarity=0.5523
4. faqs.jsonl | similarity=0.4528

======================================================================
QUERY: Where can I track my package?
1. faqs.jsonl | similarity=0.5947
2. faqs.jsonl | similarity=0.5789
3. shipping_and_delivery.md | similarity=0.4994
4. faqs.jsonl | similarity=0.4596

======================================================================
QUERY: What is the weather today?
1. faqs.jsonl | similarity=0.1289
2. faqs.jsonl | similarity=0.0727
3. shipping_and_delivery.md | similarity=0.0674
4. faqs.jsonl | similarity=0.0557

===== DIAGNOSTIC FINISHED =====

Note: This cell only measures retrieval scores.
It does not modify the index or configuration.

✅ CELL COMPLETED

In [40]:
print("===== RETRIEVAL THRESHOLD SENSITIVITY TEST =====")

queries = [
    ("How can I reset my password?", "account_security.md"),
    ("I was charged twice for the same payment.", "billing_and_invoices.md"),
    ("Can I get a refund for my subscription?", "cancellation_and_refunds.md"),
    ("Where can I track my package?", "shipping_and_delivery.md"),
    ("What is the weather today?", None),
]

thresholds = [0.55, 0.50, 0.45, 0.40]

for threshold in thresholds:
    print(f"\n{'=' * 70}")
    print(f"THRESHOLD: {threshold}")

    for query, expected_document in queries:
        results = store.search(
            query=query,
            embedder=embedder,
            top_k=3,
            threshold=threshold
        )

        if results:
            top = results[0]
            status = (
                "CORRECT"
                if expected_document == top["document"]
                else "INCORRECT"
            )

            print(
                f"\nQuery: {query}\n"
                f"Top document: {top['document']}\n"
                f"Similarity: {top['similarity']}\n"
                f"Expected: {expected_document}\n"
                f"Status: {status}"
            )
        else:
            print(
                f"\nQuery: {query}\n"
                f"No document retrieved"
            )

print("\n===== THRESHOLD TEST FINISHED =====")
print("\n✅ CELL COMPLETED")

===== RETRIEVAL THRESHOLD SENSITIVITY TEST =====

======================================================================
THRESHOLD: 0.55

Query: How can I reset my password?
Top document: faqs.jsonl
Similarity: 0.7173
Expected: account_security.md
Status: INCORRECT

Query: I was charged twice for the same payment.
Top document: faqs.jsonl
Similarity: 0.6149
Expected: billing_and_invoices.md
Status: INCORRECT

Query: Can I get a refund for my subscription?
Top document: cancellation_and_refunds.md
Similarity: 0.6682
Expected: cancellation_and_refunds.md
Status: CORRECT

Query: Where can I track my package?
Top document: faqs.jsonl
Similarity: 0.5947
Expected: shipping_and_delivery.md
Status: INCORRECT

Query: What is the weather today?
No document retrieved

======================================================================
THRESHOLD: 0.5

Query: How can I reset my password?
Top document: faqs.jsonl
Similarity: 0.7173
Expected: account_security.md
Status: INCORRECT

Query: I was charged twice for the same payment.
Top document: faqs.jsonl
Similarity: 0.6149
Expected: billing_and_invoices.md
Status: INCORRECT

Query: Can I get a refund for my subscription?
Top document: cancellation_and_refunds.md
Similarity: 0.6682
Expected: cancellation_and_refunds.md
Status: CORRECT

Query: Where can I track my package?
Top document: faqs.jsonl
Similarity: 0.5947
Expected: shipping_and_delivery.md
Status: INCORRECT

Query: What is the weather today?
No document retrieved

======================================================================
THRESHOLD: 0.45

Query: How can I reset my password?
Top document: faqs.jsonl
Similarity: 0.7173
Expected: account_security.md
Status: INCORRECT

Query: I was charged twice for the same payment.
Top document: faqs.jsonl
Similarity: 0.6149
Expected: billing_and_invoices.md
Status: INCORRECT

Query: Can I get a refund for my subscription?
Top document: cancellation_and_refunds.md
Similarity: 0.6682
Expected: cancellation_and_refunds.md
Status: CORRECT

Query: Where can I track my package?
Top document: faqs.jsonl
Similarity: 0.5947
Expected: shipping_and_delivery.md
Status: INCORRECT

Query: What is the weather today?
No document retrieved

======================================================================
THRESHOLD: 0.4

Query: How can I reset my password?
Top document: faqs.jsonl
Similarity: 0.7173
Expected: account_security.md
Status: INCORRECT

Query: I was charged twice for the same payment.
Top document: faqs.jsonl
Similarity: 0.6149
Expected: billing_and_invoices.md
Status: INCORRECT

Query: Can I get a refund for my subscription?
Top document: cancellation_and_refunds.md
Similarity: 0.6682
Expected: cancellation_and_refunds.md
Status: CORRECT

Query: Where can I track my package?
Top document: faqs.jsonl
Similarity: 0.5947
Expected: shipping_and_delivery.md
Status: INCORRECT

Query: What is the weather today?
No document retrieved

===== THRESHOLD TEST FINISHED =====

✅ CELL COMPLETED

In [41]:
print("===== RETRIEVER INTEGRATION TEST =====")

# Create a fresh retriever from the persisted store.
test_retriever = Retriever(
    embedder=embedder,
    store=store
)

test_queries = [
    "How can I reset my password?",
    "I was charged twice for the same payment.",
    "Can I get a refund for my subscription?",
    "Where can I track my package?",
    "What is the weather today?",
]

for query in test_queries:
    print(f"\nQuery: {query}")

    results = test_retriever.search(
        query,
        top_k=3,
        threshold=0.45
    )

    if results:
        for rank, result in enumerate(results, 1):
            print(
                f"  {rank}. {result['document']} "
                f"(similarity={result['similarity']})"
            )
    else:
        print("  No relevant results")

print("\n===== RETRIEVER INTEGRATION TEST FINISHED =====")
print("\n✅ CELL COMPLETED")

===== RETRIEVER INTEGRATION TEST =====

Query: How can I reset my password?
  1. faqs.jsonl (similarity=0.7173)
  2. account_security.md (similarity=0.5058)

Query: I was charged twice for the same payment.
  1. faqs.jsonl (similarity=0.6149)
  2. billing_and_invoices.md (similarity=0.5301)

Query: Can I get a refund for my subscription?
  1. cancellation_and_refunds.md (similarity=0.6682)
  2. faqs.jsonl (similarity=0.6389)
  3. faqs.jsonl (similarity=0.5523)

Query: Where can I track my package?
  1. faqs.jsonl (similarity=0.5947)
  2. faqs.jsonl (similarity=0.5789)
  3. shipping_and_delivery.md (similarity=0.4994)

Query: What is the weather today?
  No relevant results

===== RETRIEVER INTEGRATION TEST FINISHED =====

✅ CELL COMPLETED

In [42]:
import importlib
import src.rag.pipeline
import src.models.train_transformer

importlib.reload(src.rag.pipeline)

In [43]:
# testing Rag end to end
print("===== RAG END-TO-END TEST =====")

from src.rag.pipeline import RAGPipeline
from src.llm.provider import MockLLMClient

# Use the existing retriever from Cell 36
mock_llm = MockLLMClient()

rag = RAGPipeline(
    retriever=test_retriever,
    llm=mock_llm
)

rag_queries = [
    "How can I reset my password?",
    "I was charged twice for the same payment.",
    "Can I get a refund for my subscription?",
    "Where can I track my package?",
    "What is the weather today?",
]

for query in rag_queries:
    print(f"\nQuery: {query}")

    result = rag.answer(
        query=query,
        intent_confidence=0.90
    )

    print("Answer:", result["answer"])
    print("Confidence:", result["confidence"])
    print("Escalate:", result["escalate"])
    print("Sources:", result["sources"])
    print("Retrieval latency:", result["retrieval_latency_ms"], "ms")

    if "generation_latency_ms" in result:
        print("Generation latency:", result["generation_latency_ms"], "ms")

    if result["escalation_reason"]:
        print("Escalation reason:", result["escalation_reason"])

print("\n===== RAG END-TO-END TEST FINISHED =====")
print("✅ CELL COMPLETED")

===== RAG END-TO-END TEST =====

Query: How can I reset my password?
Answer: Based on the available support policy: [Source 1: faqs.jsonl; chunk faqs_jsonl_0004]
Confidence: high
Escalate: False
Sources: [{'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0004', 'similarity': 0.7173}]
Retrieval latency: 8.97 ms
Generation latency: 0.0 ms

Query: I was charged twice for the same payment.
Answer: Based on the available support policy: [Source 1: faqs.jsonl; chunk faqs_jsonl_0008]
Confidence: high
Escalate: False
Sources: [{'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0008', 'similarity': 0.6149}]
Retrieval latency: 6.45 ms
Generation latency: 0.0 ms

Query: Can I get a refund for my subscription?
Answer: Based on the available support policy: [Source 1: cancellation_and_refunds.md; chunk cancellation_and_refunds_md_0000]
Confidence: high
Escalate: False
Sources: [{'document': 'cancellation_and_refunds.md', 'page': None, 'chunk_id': 'cancellation_and_refunds_md_0000', 'similarity': 0.6682}, {'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0001', 'similarity': 0.6389}, {'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0000', 'similarity': 0.5523}]
Retrieval latency: 7.1 ms
Generation latency: 0.0 ms

Query: Where can I track my package?
Answer: Based on the available support policy: [Source 1: faqs.jsonl; chunk faqs_jsonl_0014]
Confidence: high
Escalate: False
Sources: [{'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0014', 'similarity': 0.5947}, {'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0012', 'similarity': 0.5789}]
Retrieval latency: 6.12 ms
Generation latency: 0.0 ms

Query: What is the weather today?
Answer: I couldn't find sufficient information in the available support knowledge. This case should be reviewed by a support agent.
Confidence: low
Escalate: True
Sources: []
Retrieval latency: 5.9 ms
Escalation reason: Relevant company knowledge could not be confidently retrieved.

===== RAG END-TO-END TEST FINISHED =====
✅ CELL COMPLETED

In [44]:
# evaluating queries and retrieval
print("===== RETRIEVAL EVALUATION =====")

from src.retrieval.retriever import Retriever

eval_queries = [
    {
        "query": "How can I reset my password?",
        "relevant_document": "account_security.md"
    },
    {
        "query": "I was charged twice for the same payment.",
        "relevant_document": "billing_and_invoices.md"
    },
    {
        "query": "Can I get a refund for my subscription?",
        "relevant_document": "cancellation_and_refunds.md"
    },
    {
        "query": "Where can I track my package?",
        "relevant_document": "shipping_and_delivery.md"
    },
    {
        "query": "What is the weather today?",
        "relevant_document": None
    }
]

def evaluate_retrieval(threshold):
    retriever = Retriever(
        embedder=embedder,
        store=store
    )

    results = []

    for item in eval_queries:
        retrieved = retriever.search(
            item["query"],
            top_k=3,
            threshold=threshold
        )

        documents = [r["document"] for r in retrieved]
        relevant = item["relevant_document"]

        if relevant is None:
            recall = 1.0 if len(documents) == 0 else 0.0
            precision = 1.0 if len(documents) == 0 else 0.0
            rr = 1.0 if len(documents) == 0 else 0.0
        else:
            hit_positions = [
                i + 1
                for i, doc in enumerate(documents)
                if doc == relevant
            ]

            recall = 1.0 if hit_positions else 0.0
            precision = (
                sum(doc == relevant for doc in documents) / len(documents)
                if documents else 0.0
            )
            rr = 1.0 / hit_positions[0] if hit_positions else 0.0

        results.append({
            "query": item["query"],
            "relevant": relevant,
            "retrieved": documents,
            "recall": recall,
            "precision": precision,
            "rr": rr
        })

    return results


for threshold in [0.45, 0.50, 0.55]:
    results = evaluate_retrieval(threshold)

    recall_at_3 = sum(r["recall"] for r in results) / len(results)
    precision_at_3 = sum(r["precision"] for r in results) / len(results)
    mrr = sum(r["rr"] for r in results) / len(results)

    print(f"\nThreshold: {threshold}")
    print(f"Recall@3:    {recall_at_3:.4f}")
    print(f"Precision@3: {precision_at_3:.4f}")
    print(f"MRR:         {mrr:.4f}")

print("\n===== RETRIEVAL EVALUATION FINISHED =====")
print("✅ CELL COMPLETED")

===== RETRIEVAL EVALUATION =====

Threshold: 0.45
Recall@3:    1.0000
Precision@3: 0.5333
MRR:         0.6667

Threshold: 0.5
Recall@3:    0.8000
Precision@3: 0.4667
MRR:         0.6000

Threshold: 0.55
Recall@3:    0.4000
Precision@3: 0.2667
MRR:         0.4000

===== RETRIEVAL EVALUATION FINISHED =====
✅ CELL COMPLETED

In [45]:
print("===== RAG THRESHOLD VALIDATION =====")

from src.config import get_settings

settings = get_settings()

print("Configured threshold:", settings.rag.similarity_threshold)

original_threshold = settings.rag.similarity_threshold
settings.rag.similarity_threshold = 0.45

rag_045 = RAGPipeline(
    retriever=test_retriever,
    llm=MockLLMClient()
)

validation_queries = [
    "How can I reset my password?",
    "I was charged twice for the same payment.",
    "Can I get a refund for my subscription?",
    "Where can I track my package?",
    "What is the weather today?",
]

for query in validation_queries:
    result = rag_045.answer(
        query=query,
        intent_confidence=0.90
    )

    print(f"\nQuery: {query}")
    print("Confidence:", result["confidence"])
    print("Escalate:", result["escalate"])
    print("Sources:", result["sources"])

# Restore the original configuration after testing.
settings.rag.similarity_threshold = original_threshold

print("\nOriginal threshold restored:", settings.rag.similarity_threshold)

print("\n===== RAG THRESHOLD VALIDATION FINISHED =====")
print("✅ CELL COMPLETED")

===== RAG THRESHOLD VALIDATION =====
Configured threshold: 0.55

Query: How can I reset my password?
Confidence: high
Escalate: False
Sources: [{'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0004', 'similarity': 0.7173}, {'document': 'account_security.md', 'page': None, 'chunk_id': 'account_security_md_0000', 'similarity': 0.5058}]

Query: I was charged twice for the same payment.
Confidence: high
Escalate: False
Sources: [{'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0008', 'similarity': 0.6149}, {'document': 'billing_and_invoices.md', 'page': None, 'chunk_id': 'billing_and_invoices_md_0000', 'similarity': 0.5301}]

Query: Can I get a refund for my subscription?
Confidence: high
Escalate: False
Sources: [{'document': 'cancellation_and_refunds.md', 'page': None, 'chunk_id': 'cancellation_and_refunds_md_0000', 'similarity': 0.6682}, {'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0001', 'similarity': 0.6389}, {'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0000', 'similarity': 0.5523}]

Query: Where can I track my package?
Confidence: high
Escalate: False
Sources: [{'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0014', 'similarity': 0.5947}, {'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0012', 'similarity': 0.5789}, {'document': 'shipping_and_delivery.md', 'page': None, 'chunk_id': 'shipping_and_delivery_md_0000', 'similarity': 0.4994}]

Query: What is the weather today?
Confidence: low
Escalate: True
Sources: []

Original threshold restored: 0.55

===== RAG THRESHOLD VALIDATION FINISHED =====
✅ CELL COMPLETED

In [46]:
print("===== PROJECT RAG EVALUATION =====")

from scripts.evaluate import evaluate_rag

result = evaluate_rag()

print("\n===== RAG RETRIEVAL METRICS =====")

for metric, value in result.items():
    print(f"{metric}: {value}")

print("\n===== EVALUATION REPORT =====")

from src.config import get_settings
from pathlib import Path

settings = get_settings()

report_path = Path(
    settings.path(
        "artifacts/evaluation_reports/rag_retrieval_report.json"
    )
)

print("Report exists:", report_path.exists())
print("Report path:", report_path)

if report_path.exists():
    print("\nReport contents:")
    print(report_path.read_text(encoding="utf-8"))

print("✅ CELL COMPLETED")

===== PROJECT RAG EVALUATION =====

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

===== RAG RETRIEVAL METRICS =====
recall_at_k: 0.8333
precision_at_k: 1.0
mrr: 1.0

===== EVALUATION REPORT =====
Report exists: True
Report path: /content/ai-customer-support-intelligence/artifacts/evaluation_reports/rag_retrieval_report.json

Report contents:
{
  "cases": [
    {
      "query": "How long before a refund appears on my card?",
      "relevant": [
        "faqs.jsonl",
        "cancellation_and_refunds.md"
      ]
    },
    {
      "query": "My tracking says delivered but the package is missing.",
      "relevant": [
        "faqs.jsonl",
        "shipping_and_delivery.md"
      ]
    },
    {
      "query": "My 2FA code does not arrive.",
      "relevant": [
        "faqs.jsonl",
        "account_security.md"
      ]
    }
  ],
  "metrics": {
    "recall_at_k": 0.8333,
    "precision_at_k": 1.0,
    "mrr": 1.0
  },
  "note": "Small manual evaluation set; expand for reliable conclusions."
}
✅ CELL COMPLETED

In [47]:
print("===== RAG EVALUATION CASE ANALYSIS =====")

from scripts.evaluate import RAG_CASES
from src.retrieval.retriever import Retriever

evaluation_retriever = Retriever()

for i, case in enumerate(RAG_CASES, 1):
    print(f"\n{'=' * 70}")
    print(f"CASE {i}")
    print("Query:", case["query"])
    print("Expected:", case["relevant"])

    results = evaluation_retriever.search(
        case["query"],
        top_k=10,
        threshold=-1
    )

    print("\nRetrieved ranking:")

    for rank, result in enumerate(results, 1):
        marker = "✅ EXPECTED" if result["document"] in case["relevant"] else "❌ OTHER"

        print(
            f"  {rank}. {result['document']} "
            f"| similarity={result['similarity']:.4f} "
            f"| {marker}"
        )

print("✅ CELL COMPLETED")

===== RAG EVALUATION CASE ANALYSIS =====

======================================================================
CASE 1
Query: How long before a refund appears on my card?
Expected: ['faqs.jsonl', 'cancellation_and_refunds.md']

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Retrieved ranking:
  1. faqs.jsonl | similarity=0.7054 | ✅ EXPECTED
  2. faqs.jsonl | similarity=0.6061 | ✅ EXPECTED
  3. faqs.jsonl | similarity=0.5022 | ✅ EXPECTED
  4. cancellation_and_refunds.md | similarity=0.4871 | ✅ EXPECTED
  5. faqs.jsonl | similarity=0.4212 | ✅ EXPECTED
  6. faqs.jsonl | similarity=0.3999 | ✅ EXPECTED
  7. billing_and_invoices.md | similarity=0.3879 | ❌ OTHER
  8. faqs.jsonl | similarity=0.3241 | ✅ EXPECTED
  9. faqs.jsonl | similarity=0.3009 | ✅ EXPECTED
  10. faqs.jsonl | similarity=0.2901 | ✅ EXPECTED

======================================================================
CASE 2
Query: My tracking says delivered but the package is missing.
Expected: ['faqs.jsonl', 'shipping_and_delivery.md']

Retrieved ranking:
  1. faqs.jsonl | similarity=0.7442 | ✅ EXPECTED
  2. shipping_and_delivery.md | similarity=0.6078 | ✅ EXPECTED
  3. faqs.jsonl | similarity=0.5758 | ✅ EXPECTED
  4. faqs.jsonl | similarity=0.5206 | ✅ EXPECTED
  5. faqs.jsonl | similarity=0.3170 | ✅ EXPECTED
  6. faqs.jsonl | similarity=0.2645 | ✅ EXPECTED
  7. cancellation_and_refunds.md | similarity=0.2376 | ❌ OTHER
  8. faqs.jsonl | similarity=0.2321 | ✅ EXPECTED
  9. faqs.jsonl | similarity=0.1775 | ✅ EXPECTED
  10. faqs.jsonl | similarity=0.1668 | ✅ EXPECTED

======================================================================
CASE 3
Query: My 2FA code does not arrive.
Expected: ['faqs.jsonl', 'account_security.md']

Retrieved ranking:
  1. faqs.jsonl | similarity=0.7353 | ✅ EXPECTED
  2. account_security.md | similarity=0.5610 | ✅ EXPECTED
  3. faqs.jsonl | similarity=0.2798 | ✅ EXPECTED
  4. faqs.jsonl | similarity=0.2793 | ✅ EXPECTED
  5. shipping_and_delivery.md | similarity=0.2176 | ❌ OTHER
  6. faqs.jsonl | similarity=0.2124 | ✅ EXPECTED
  7. faqs.jsonl | similarity=0.1933 | ✅ EXPECTED
  8. faqs.jsonl | similarity=0.1905 | ✅ EXPECTED
  9. cancellation_and_refunds.md | similarity=0.1900 | ❌ OTHER
  10. faqs.jsonl | similarity=0.1877 | ✅ EXPECTED
✅ CELL COMPLETED

In [48]:
print("===== FAQ JSONL FORMAT INSPECTION =====")

from pathlib import Path
import json

faq_path = Path("data/knowledge_base/faqs.jsonl")

print("File exists:", faq_path.exists())
print("File size:", faq_path.stat().st_size, "bytes")

print("\n===== FIRST 5 FAQ RECORDS =====")

with faq_path.open("r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        if i >= 5:
            break

        record = json.loads(line)

        print(f"\nRecord {i + 1}:")
        print(json.dumps(record, indent=2, ensure_ascii=False))

print("✅ CELL COMPLETED")

===== FAQ JSONL FORMAT INSPECTION =====
File exists: True
File size: 7902 bytes

===== FIRST 5 FAQ RECORDS =====

Record 1:
{
  "id": "faq-01",
  "category": "cancellation_and_refund",
  "question": "How do I request a refund for an accidental purchase or duplicate order?",
  "answer": "You can request a full refund within 30 days of purchase under our 30-day money-back guarantee. Go to Account Settings > Billing & Subscriptions and click 'Request Refund', or submit a ticket with your transaction ID."
}

Record 2:
{
  "id": "faq-02",
  "category": "cancellation_and_refund",
  "question": "Can I cancel my subscription and get a prorated refund?",
  "answer": "Annual plan subscribers can cancel anytime and receive a prorated refund for unused full calendar months, subject to a 10% administrative fee. Monthly subscriptions remain active until the end of the paid billing cycle without refunds."
}

Record 3:
{
  "id": "faq-03",
  "category": "cancellation_and_refund",
  "question": "How long does it take for a refund to show up on my credit card statement?",
  "answer": "Once approved, refunds are processed immediately. Depending on your financial institution, funds typically appear on your statement within 3 to 5 business days."
}

Record 4:
{
  "id": "faq-04",
  "category": "cancellation_and_refund",
  "question": "What is the return policy for damaged or defective physical products?",
  "answer": "Defective physical items must be returned within 14 calendar days of delivery with original packaging. Customer support provides a prepaid return shipping label upon photo verification of damage."
}

Record 5:
{
  "id": "faq-05",
  "category": "account_access",
  "question": "How do I reset my account password if I forgot it?",
  "answer": "Click 'Forgot Password' on the login screen, enter your registered email, and a secure password reset link valid for 15 minutes will be emailed to you."
}
✅ CELL COMPLETED

In [49]:
print("===== JSONL KNOWLEDGE INGESTION TEST =====")

from src.knowledge.loader import KnowledgeLoader

loader = KnowledgeLoader("data/knowledge_base")
documents = loader.load()

faq_docs = [
    doc for doc in documents
    if doc.metadata.get("document") == "faqs.jsonl"
]

print("Total loaded documents:", len(documents))
print("FAQ records loaded:", len(faq_docs))

print("\nDocument counts:")

from collections import Counter

counts = Counter(
    doc.metadata.get("document")
    for doc in documents
)

for document, count in counts.items():
    print(f"  {document}: {count}")

print("\nFirst 3 FAQ records:")

for doc in faq_docs[:3]:
    print("\nDocument:", doc.metadata.get("document"))
    print("FAQ ID:", doc.metadata.get("faq_id"))
    print("Category:", doc.metadata.get("category"))
    print("Line:", doc.metadata.get("line"))
    print("Text:", doc.text)

print("✅ CELL COMPLETED")

===== JSONL KNOWLEDGE INGESTION TEST =====
Total loaded documents: 28
FAQ records loaded: 24

Document counts:
  account_security.md: 1
  billing_and_invoices.md: 1
  cancellation_and_refunds.md: 1
  faqs.jsonl: 24
  shipping_and_delivery.md: 1

First 3 FAQ records:

Document: faqs.jsonl
FAQ ID: faq-01
Category: cancellation_and_refund
Line: 1
Text: Question: How do I request a refund for an accidental purchase or duplicate order?
Answer: You can request a full refund within 30 days of purchase under our 30-day money-back guarantee. Go to Account Settings > Billing & Subscriptions and click 'Request Refund', or submit a ticket with your transaction ID.

Document: faqs.jsonl
FAQ ID: faq-02
Category: cancellation_and_refund
Line: 2
Text: Question: Can I cancel my subscription and get a prorated refund?
Answer: Annual plan subscribers can cancel anytime and receive a prorated refund for unused full calendar months, subject to a 10% administrative fee. Monthly subscriptions remain active until the end of the paid billing cycle without refunds.

Document: faqs.jsonl
FAQ ID: faq-03
Category: cancellation_and_refund
Line: 3
Text: Question: How long does it take for a refund to show up on my credit card statement?
Answer: Once approved, refunds are processed immediately. Depending on your financial institution, funds typically appear on your statement within 3 to 5 business days.
✅ CELL COMPLETED

In [50]:
print("===== RELOADING KNOWLEDGE LOADER =====")

import importlib
import src.knowledge.loader as loader_module

# Force Python to reload the modified source file
importlib.reload(loader_module)

KnowledgeLoader = loader_module.KnowledgeLoader

loader = KnowledgeLoader("data/knowledge_base")
documents = loader.load()

faq_docs = [
    doc for doc in documents
    if doc.metadata.get("document") == "faqs.jsonl"
]

print("Total loaded documents:", len(documents))
print("FAQ records loaded:", len(faq_docs))

print("\nDocument counts:")

from collections import Counter

counts = Counter(
    doc.metadata.get("document")
    for doc in documents
)

for document, count in counts.items():
    print(f"  {document}: {count}")

print("\nFirst 3 FAQ records:")

for doc in faq_docs[:3]:
    print("\nFAQ ID:", doc.metadata.get("faq_id"))
    print("Category:", doc.metadata.get("category"))
    print("Line:", doc.metadata.get("line"))
    print("Text:", doc.text)

print("✅ CELL COMPLETED")

===== RELOADING KNOWLEDGE LOADER =====
Total loaded documents: 28
FAQ records loaded: 24

Document counts:
  account_security.md: 1
  billing_and_invoices.md: 1
  cancellation_and_refunds.md: 1
  faqs.jsonl: 24
  shipping_and_delivery.md: 1

First 3 FAQ records:

FAQ ID: faq-01
Category: cancellation_and_refund
Line: 1
Text: Question: How do I request a refund for an accidental purchase or duplicate order?
Answer: You can request a full refund within 30 days of purchase under our 30-day money-back guarantee. Go to Account Settings > Billing & Subscriptions and click 'Request Refund', or submit a ticket with your transaction ID.

FAQ ID: faq-02
Category: cancellation_and_refund
Line: 2
Text: Question: Can I cancel my subscription and get a prorated refund?
Answer: Annual plan subscribers can cancel anytime and receive a prorated refund for unused full calendar months, subject to a 10% administrative fee. Monthly subscriptions remain active until the end of the paid billing cycle without refunds.

FAQ ID: faq-03
Category: cancellation_and_refund
Line: 3
Text: Question: How long does it take for a refund to show up on my credit card statement?
Answer: Once approved, refunds are processed immediately. Depending on your financial institution, funds typically appear on your statement within 3 to 5 business days.
✅ CELL COMPLETED

In [51]:
print("===== REBUILDING FAISS KNOWLEDGE INDEX =====")

from src.knowledge.loader import KnowledgeLoader
from src.knowledge.chunker import DocumentChunker
from src.embeddings.embedder import SentenceEmbeddingModel
from src.retrieval.vector_store import FAISSVectorStore

# 1. Load all knowledge-base documents
loader = KnowledgeLoader("data/knowledge_base")
documents = loader.load()

# 2. Convert documents into searchable chunks
chunker = DocumentChunker(
    chunk_size=800,
    chunk_overlap=120
)
chunks = chunker.chunk(documents)

print("Documents loaded:", len(documents))
print("Chunks created:", len(chunks))

# 3. Load embedding model
embedder = SentenceEmbeddingModel(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding dimension:", embedder.dimension)

# 4. Rebuild persistent FAISS index
store = FAISSVectorStore(
    index_path="models/embeddings/faiss.index",
    metadata_path="models/embeddings/metadata.json"
)

store.build(
    chunks=chunks,
    embedder=embedder
)

print("\n===== INDEX REBUILT =====")
print("FAISS vectors:", store.index.ntotal)
print("FAISS dimension:", store.index.d)

# 5. Verify FAQ chunks are present
faq_chunks = [
    chunk for chunk in chunks
    if chunk.get("document") == "faqs.jsonl"
]

print("FAQ chunks indexed:", len(faq_chunks))

if faq_chunks:
    print("\nExample FAQ chunk:")
    print(faq_chunks[0])

print("✅ CELL COMPLETED")

===== REBUILDING FAISS KNOWLEDGE INDEX =====
Documents loaded: 28
Chunks created: 28

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding dimension: 384

===== INDEX REBUILT =====
FAISS vectors: 28
FAISS dimension: 384
FAQ chunks indexed: 24

Example FAQ chunk:
{'chunk_id': 'faqs_jsonl_0000', 'text': "Question: How do I request a refund for an accidental purchase or duplicate order? Answer: You can request a full refund within 30 days of purchase under our 30-day money-back guarantee. Go to Account Settings > Billing & Subscriptions and click 'Request Refund', or submit a ticket with your transaction ID.", 'document': 'faqs.jsonl', 'page': None, 'section': None}
✅ CELL COMPLETED

/content/ai-customer-support-intelligence/src/embeddings/embedder.py:34: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  return int(self._load().get_sentence_embedding_dimension())

In [52]:
print("===== FAQ-AWARE RETRIEVAL TEST =====")

from src.embeddings.embedder import SentenceEmbeddingModel
from src.retrieval.vector_store import FAISSVectorStore
from src.retrieval.retriever import Retriever

# Reload the persistent index
embedder = SentenceEmbeddingModel(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

store = FAISSVectorStore(
    index_path="models/embeddings/faiss.index",
    metadata_path="models/embeddings/metadata.json"
)
store.load()

retriever = Retriever(
    embedder=embedder,
    store=store
)

test_queries = [
    "How long before a refund appears on my card?",
    "My tracking says delivered but the package is missing.",
    "My 2FA code does not arrive.",
    "How do I reset my password?",
    "I was charged twice for the same payment.",
    "What is the weather today?"
]

for query in test_queries:
    print("\n" + "=" * 80)
    print("QUERY:", query)

    results = retriever.search(
        query,
        top_k=3,
        threshold=0.0
    )

    if not results:
        print("No results.")
        continue

    for i, result in enumerate(results, 1):
        print(f"\n{i}. Document: {result['document']}")
        print(f"   Similarity: {result['similarity']:.4f}")
        print(f"   Chunk ID: {result['chunk_id']}")
        print(f"   Text: {result['text'][:220]}...")

print("✅ CELL COMPLETED")

===== FAQ-AWARE RETRIEVAL TEST =====

================================================================================
QUERY: How long before a refund appears on my card?

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

1. Document: faqs.jsonl
   Similarity: 0.7054
   Chunk ID: faqs_jsonl_0002
   Text: Question: How long does it take for a refund to show up on my credit card statement? Answer: Once approved, refunds are processed immediately. Depending on your financial institution, funds typically appear on your state...

2. Document: faqs.jsonl
   Similarity: 0.6061
   Chunk ID: faqs_jsonl_0000
   Text: Question: How do I request a refund for an accidental purchase or duplicate order? Answer: You can request a full refund within 30 days of purchase under our 30-day money-back guarantee. Go to Account Settings > Billing ...

3. Document: faqs.jsonl
   Similarity: 0.5022
   Chunk ID: faqs_jsonl_0011
   Text: Question: My payment failed due to insufficient funds. When will you retry charging my card? Answer: Our billing system automatically retries failed payments on Day 1, Day 4, and Day 7. A 7-day grace period is provided b...

================================================================================
QUERY: My tracking says delivered but the package is missing.

1. Document: faqs.jsonl
   Similarity: 0.7442
   Chunk ID: faqs_jsonl_0014
   Text: Question: What should I do if tracking says delivered but I did not receive my package? Answer: First check surrounding areas and with neighbors. Couriers occasionally scan deliveries prematurely. If the parcel does not ...

2. Document: shipping_and_delivery.md
   Similarity: 0.6078
   Chunk ID: shipping_and_delivery_md_0000
   Text: # Shipping, Tracking, and Delivery Policies ## 1. Tracking Status Updates Carrier tracking numbers are assigned within 24 hours of order fulfillment. Tracking scans may take up to 48 hours to update once the carrier take...

3. Document: faqs.jsonl
   Similarity: 0.5758
   Chunk ID: faqs_jsonl_0012
   Text: Question: How can I track the shipping and delivery status of my order? Answer: Once your order ships, a tracking number and courier link are emailed to you. You can also view live tracking status anytime in your account...

================================================================================
QUERY: My 2FA code does not arrive.

1. Document: faqs.jsonl
   Similarity: 0.7353
   Chunk ID: faqs_jsonl_0005
   Text: Question: What should I do if my Two-Factor Authentication 2FA code is not working? Answer: Use one of your 10 emergency backup recovery codes generated during 2FA setup. If you do not have backup codes, submit an identi...

2. Document: account_security.md
   Similarity: 0.5610
   Chunk ID: account_security_md_0000
   Text: # Account Security and Authentication Guide ## 1. Password Reset Procedures If you have forgotten your password or your reset link has expired: 1. Go to the login screen and click **Forgot Password**. 2. Enter your prima...

3. Document: faqs.jsonl
   Similarity: 0.2798
   Chunk ID: faqs_jsonl_0013
   Text: Question: Why has my tracking number not updated for several days? Answer: Tracking numbers are generated when the label is printed. Carrier scans may take 24 to 48 hours to update once the carrier physically scans the p...

================================================================================
QUERY: How do I reset my password?

1. Document: faqs.jsonl
   Similarity: 0.7151
   Chunk ID: faqs_jsonl_0004
   Text: Question: How do I reset my account password if I forgot it? Answer: Click 'Forgot Password' on the login screen, enter your registered email, and a secure password reset link valid for 15 minutes will be emailed to you....

2. Document: account_security.md
   Similarity: 0.4987
   Chunk ID: account_security_md_0000
   Text: # Account Security and Authentication Guide ## 1. Password Reset Procedures If you have forgotten your password or your reset link has expired: 1. Go to the login screen and click **Forgot Password**. 2. Enter your prima...

3. Document: faqs.jsonl
   Similarity: 0.4100
   Chunk ID: faqs_jsonl_0006
   Text: Question: Why is my account locked or suspended due to failed login attempts? Answer: For security protection, accounts are temporarily locked for 30 minutes after 5 consecutive failed login attempts. You can wait 30 min...

================================================================================
QUERY: I was charged twice for the same payment.

1. Document: faqs.jsonl
   Similarity: 0.6149
   Chunk ID: faqs_jsonl_0008
   Text: Question: Why was my credit card charged twice for the same billing period? Answer: Duplicate charges usually result from network timeouts during checkout. The duplicate pre-authorization hold will automatically fall off...

2. Document: billing_and_invoices.md
   Similarity: 0.5301
   Chunk ID: billing_and_invoices_md_0000
   Text: # Billing and Invoicing Policies ## 1. Duplicate Charges and Billing Disputes If your credit card or bank account shows duplicate charges for the same billing cycle: 1. Contact support immediately with your transaction r...

3. Document: faqs.jsonl
   Similarity: 0.4320
   Chunk ID: faqs_jsonl_0000
   Text: Question: How do I request a refund for an accidental purchase or duplicate order? Answer: You can request a full refund within 30 days of purchase under our 30-day money-back guarantee. Go to Account Settings > Billing ...

================================================================================
QUERY: What is the weather today?

1. Document: faqs.jsonl
   Similarity: 0.1289
   Chunk ID: faqs_jsonl_0020
   Text: Question: What are customer support business hours and response times? Answer: Our standard customer support operates Monday through Friday, 9:00 AM to 6:00 PM EST. Critical severity issues for enterprise tier customers ...

2. Document: faqs.jsonl
   Similarity: 0.0727
   Chunk ID: faqs_jsonl_0012
   Text: Question: How can I track the shipping and delivery status of my order? Answer: Once your order ships, a tracking number and courier link are emailed to you. You can also view live tracking status anytime in your account...

3. Document: shipping_and_delivery.md
   Similarity: 0.0674
   Chunk ID: shipping_and_delivery_md_0000
   Text: # Shipping, Tracking, and Delivery Policies ## 1. Tracking Status Updates Carrier tracking numbers are assigned within 24 hours of order fulfillment. Tracking scans may take up to 48 hours to update once the carrier take...
✅ CELL COMPLETED

In [53]:
print("===== OFFICIAL RAG EVALUATION AFTER FAQ FIX =====")

from scripts.evaluate import evaluate_rag

result = evaluate_rag()

print("\nRAG Evaluation Results:")
for metric, value in result.items():
    print(f"{metric}: {value}")

print("✅ CELL COMPLETED")

===== OFFICIAL RAG EVALUATION AFTER FAQ FIX =====

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

RAG Evaluation Results:
recall_at_k: 0.8333
precision_at_k: 1.0
mrr: 1.0
✅ CELL COMPLETED

In [54]:
print("===== RE-RUNNING OFFICIAL RAG EVALUATION =====")

import importlib
import scripts.evaluate as evaluate_module
importlib.reload(evaluate_module)

result = evaluate_module.evaluate_rag()

print("\nCorrected RAG Evaluation Results:")
for metric, value in result.items():
    print(f"{metric}: {value}")

print("✅ CELL COMPLETED")

===== RE-RUNNING OFFICIAL RAG EVALUATION =====

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Corrected RAG Evaluation Results:
recall_at_k: 0.8333
precision_at_k: 1.0
mrr: 1.0
✅ CELL COMPLETED

In [55]:
print("===== RELOADING RAG METRICS + EVALUATION =====")

import importlib
import inspect

import src.evaluation.metrics as metrics_module
import scripts.evaluate as evaluate_module

# Reload the corrected metrics implementation first
importlib.reload(metrics_module)

# Then reload evaluate so it imports the corrected function
importlib.reload(evaluate_module)

print("\nMetric function currently loaded:")
print(
    "Duplicate-safe:",
    "unique_top" in inspect.getsource(metrics_module.retrieval_metrics)
)

result = evaluate_module.evaluate_rag()

print("\nCorrected RAG Evaluation Results:")
for metric, value in result.items():
    print(f"{metric}: {value}")

print("✅ CELL COMPLETED")

===== RELOADING RAG METRICS + EVALUATION =====

Metric function currently loaded:
Duplicate-safe: True

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Corrected RAG Evaluation Results:
recall_at_k: 0.8333
precision_at_k: 1.0
mrr: 1.0
✅ CELL COMPLETED

In [56]:
print("===== END-TO-END RAG TEST AFTER FAQ FIX =====")

from src.embeddings.embedder import SentenceEmbeddingModel
from src.retrieval.vector_store import FAISSVectorStore
from src.retrieval.retriever import Retriever
from src.rag.pipeline import RAGPipeline
from src.llm.provider import MockLLMClient

# Load the rebuilt embedding index
embedder = SentenceEmbeddingModel(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

store = FAISSVectorStore(
    index_path="models/embeddings/faiss.index",
    metadata_path="models/embeddings/metadata.json"
)
store.load()

retriever = Retriever(
    embedder=embedder,
    store=store
)

# Use the deterministic mock LLM for local testing.
# No external API key is required.
rag = RAGPipeline(
    retriever=retriever,
    llm=MockLLMClient()
)

test_queries = [
    "How long before a refund appears on my card?",
    "My tracking says delivered but the package is missing.",
    "How do I reset my password?",
    "I was charged twice for the same payment.",
    "What is the weather today?"
]

for query in test_queries:
    print("\n" + "=" * 80)
    print("QUERY:", query)

    result = rag.answer(
        query=query,
        intent_confidence=0.9
    )

    print("\nAnswer:")
    print(result.get("answer"))

    print("\nConfidence:", result.get("confidence"))
    print("Escalate:", result.get("escalate"))

    print("\nSources:")
    for source in result.get("sources", []):
        print(
            f"  - {source.get('document')} | "
            f"similarity={source.get('similarity', 0):.4f} | "
            f"chunk={source.get('chunk_id')}"
        )

print("✅ CELL COMPLETED")

===== END-TO-END RAG TEST AFTER FAQ FIX =====

================================================================================
QUERY: How long before a refund appears on my card?

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Answer:
Based on the available support policy: [Source 1: faqs.jsonl; chunk faqs_jsonl_0002]

Confidence: high
Escalate: False

Sources:
  - faqs.jsonl | similarity=0.7054 | chunk=faqs_jsonl_0002
  - faqs.jsonl | similarity=0.6061 | chunk=faqs_jsonl_0000

================================================================================
QUERY: My tracking says delivered but the package is missing.

Answer:
Based on the available support policy: [Source 1: faqs.jsonl; chunk faqs_jsonl_0014]

Confidence: high
Escalate: False

Sources:
  - faqs.jsonl | similarity=0.7442 | chunk=faqs_jsonl_0014
  - shipping_and_delivery.md | similarity=0.6078 | chunk=shipping_and_delivery_md_0000
  - faqs.jsonl | similarity=0.5758 | chunk=faqs_jsonl_0012

================================================================================
QUERY: How do I reset my password?

Answer:
Based on the available support policy: [Source 1: faqs.jsonl; chunk faqs_jsonl_0004]

Confidence: high
Escalate: False

Sources:
  - faqs.jsonl | similarity=0.7151 | chunk=faqs_jsonl_0004

================================================================================
QUERY: I was charged twice for the same payment.

Answer:
Based on the available support policy: [Source 1: faqs.jsonl; chunk faqs_jsonl_0008]

Confidence: high
Escalate: False

Sources:
  - faqs.jsonl | similarity=0.6149 | chunk=faqs_jsonl_0008

================================================================================
QUERY: What is the weather today?

Answer:
I couldn't find sufficient information in the available support knowledge. This case should be reviewed by a support agent.

Confidence: low
Escalate: True

Sources:
✅ CELL COMPLETED

In [57]:
print("===== CORRECTED SUPPORT SERVICE CHAT TEST =====")

from src.models.classical import ClassicalIntentClassifier
from src.sentiment.analyzer import SentimentAnalyzer
from src.retrieval.retriever import Retriever
from src.rag.pipeline import RAGPipeline
from src.llm.provider import MockLLMClient
from src.services.support_service import SupportService

classifier = ClassicalIntentClassifier.load(
    "models/tfidf/classical_pipeline.joblib"
)

retriever = Retriever()

rag_pipeline = RAGPipeline(
    retriever=retriever,
    llm=MockLLMClient()
)

service = SupportService(
    classifier=classifier,
    sentiment_analyzer=SentimentAnalyzer(),
    rag_pipeline=rag_pipeline,
    repository=None
)

test_messages = [
    "How long before my refund appears on my card?",
    "My tracking says delivered but I did not receive my package.",
    "I cannot access my account and I am frustrated.",
    "What is the weather today?"
]

for message in test_messages:
    print("\n" + "=" * 80)
    print("MESSAGE:", message)

    try:
        result = service.chat(
            message=message,
            conversation_id="cell61-test"
        )

        print("\nIntent:", result["intent"])
        print("Intent confidence:", result["intent_confidence"])
        print("Sentiment:", result["sentiment"])
        print("Priority:", result["priority"])
        print("Department:", result["department"])
        print("Confidence:", result["confidence"])
        print("Escalate:", result["escalate"])
        print("Escalation reason:", result["escalation_reason"])
        print("Conversation ID:", result["conversation_id"])

        print("\nAnswer:")
        print(result["answer"])

        print("\nSources:")
        for source in result.get("sources", []):
            print(
                f"  - {source['document']} | "
                f"similarity={source['similarity']:.4f} | "
                f"chunk={source['chunk_id']}"
            )

    except Exception as exc:
        print("\nCHAT ERROR:")
        print(type(exc).__name__, ":", exc)

print("✅ CELL COMPLETED")

===== CORRECTED SUPPORT SERVICE CHAT TEST =====

================================================================================
MESSAGE: How long before my refund appears on my card?

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Intent: cancellation_and_refund
Intent confidence: 0.2032
Sentiment: negative
Priority: medium
Department: billing
Confidence: low
Escalate: True
Escalation reason: Intent confidence is below the configured threshold.
Conversation ID: cell61-test

Answer:
Based on the available support policy: [Source 1: faqs.jsonl; chunk faqs_jsonl_0002]

Sources:
  - faqs.jsonl | similarity=0.6999 | chunk=faqs_jsonl_0002
  - faqs.jsonl | similarity=0.6010 | chunk=faqs_jsonl_0000

================================================================================
MESSAGE: My tracking says delivered but I did not receive my package.

Intent: order_tracking
Intent confidence: 0.2964
Sentiment: negative
Priority: medium
Department: logistics
Confidence: low
Escalate: True
Escalation reason: Intent confidence is below the configured threshold.
Conversation ID: cell61-test

Answer:
Based on the available support policy: [Source 1: faqs.jsonl; chunk faqs_jsonl_0014]

Sources:
  - faqs.jsonl | similarity=0.7737 | chunk=faqs_jsonl_0014
  - shipping_and_delivery.md | similarity=0.6029 | chunk=shipping_and_delivery_md_0000
  - faqs.jsonl | similarity=0.5858 | chunk=faqs_jsonl_0012

================================================================================
MESSAGE: I cannot access my account and I am frustrated.

Intent: account_access
Intent confidence: 0.3124
Sentiment: negative
Priority: high
Department: account_support
Confidence: low
Escalate: True
Escalation reason: Intent confidence is below the configured threshold.
Conversation ID: cell61-test

Answer:
I couldn't find sufficient information in the available support knowledge. This case should be reviewed by a support agent.

Sources:

================================================================================
MESSAGE: What is the weather today?

Intent: general_inquiry
Intent confidence: 0.2389
Sentiment: negative
Priority: medium
Department: customer_support
Confidence: low
Escalate: True
Escalation reason: Intent confidence is below the configured threshold.
Conversation ID: cell61-test

Answer:
I couldn't find sufficient information in the available support knowledge. This case should be reviewed by a support agent.

Sources:
✅ CELL COMPLETED

In [58]:
print("===== INITIALIZING DATABASE =====")

from src.database.connection import init_db, get_engine
from sqlalchemy import inspect

# Use the project's own database initialization function
init_db()

print("✓ Database initialization completed")

# Verify tables
engine = get_engine()
inspector = inspect(engine)
tables = inspector.get_table_names()

print("\n===== DATABASE TABLES =====")
for table in tables:
    print(f"✓ {table}")

required_tables = [
    "tickets",
    "triage_records",
    "rag_logs",
    "sources",
    "conversations",
    "feedback",
]

missing = [table for table in required_tables if table not in tables]

if missing:
    raise RuntimeError(
        f"Database initialization incomplete. Missing tables: {missing}"
    )

print("\n===== DATABASE INITIALIZATION PASSED =====")
print("All required tables exist.")
print("✅ CELL COMPLETED")

===== INITIALIZING DATABASE =====
✓ Database initialization completed

===== DATABASE TABLES =====
✓ conversations
✓ feedback
✓ rag_logs
✓ sources
✓ tickets
✓ triage_records

===== DATABASE INITIALIZATION PASSED =====
All required tables exist.
✅ CELL COMPLETED

In [60]:
print("===== DATABASE-BACKED CHAT TEST =====IMp")

import importlib

# Reload the updated SupportService
import src.services.support_service as support_service_module
importlib.reload(support_service_module)

from src.services.support_service import SupportService
from src.models.classical import ClassicalIntentClassifier
from src.sentiment.analyzer import SentimentAnalyzer
from src.retrieval.retriever import Retriever
from src.rag.pipeline import RAGPipeline
from src.database.repository import TicketRepository
from src.database.connection import get_session


# --------------------------------------------------
# 1. Build components
# --------------------------------------------------

classifier = ClassicalIntentClassifier.load(
    "models/tfidf/classical_pipeline.joblib"
)

sentiment_analyzer = SentimentAnalyzer()

retriever = Retriever()
rag_pipeline = RAGPipeline(retriever=retriever)

session = get_session()
repository = TicketRepository(session)

service = SupportService(
    classifier=classifier,
    sentiment_analyzer=sentiment_analyzer,
    rag_pipeline=rag_pipeline,
    repository=repository,
)

print("✓ SupportService ready")


# --------------------------------------------------
# 2. Run chat
# --------------------------------------------------

result = service.chat(
    message="I was charged $49.99 incorrectly and want a refund.",
    conversation_id="db-test-001",
)


# --------------------------------------------------
# 3. Display AI result
# --------------------------------------------------

print("\n===== CHAT RESULT =====")

for key in [
    "ticket_id",
    "intent",
    "intent_confidence",
    "sentiment",
    "sentiment_confidence",
    "priority",
    "department",
    "confidence",
    "escalate",
    "escalation_reason",
]:
    print(f"{key}: {result.get(key)}")

print("\nAnswer:")
print(result.get("answer"))

===== DATABASE-BACKED CHAT TEST =====IMp
✓ SupportService ready

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

===== CHAT RESULT =====
ticket_id: 8bec2ba0-c132-48fe-beaf-ea4813ee2139
intent: billing_and_payments
intent_confidence: 0.2263
sentiment: negative
sentiment_confidence: 0.9995
priority: high
department: billing
confidence: low
escalate: True
escalation_reason: Intent confidence is below the configured threshold.

Answer:
I couldn't find sufficient information in the available support knowledge. This case should be reviewed by a support agent.

In [61]:
print("===== FINAL DATABASE PERSISTENCE VERIFICATION =====")

ticket_id = result.get("ticket_id")

if not ticket_id:
    raise RuntimeError("No ticket ID available.")

# Fetch ticket with all related records.
ticket = repository.get_ticket_by_id(ticket_id)

if ticket is None:
    raise RuntimeError("Ticket could not be retrieved.")

print(f"\nTicket ID: {ticket.id}")


# --------------------------------------------------
# 1. Ticket
# --------------------------------------------------

print("\n===== TICKET =====")
print(f"✓ Status: {ticket.status}")
print(f"✓ Confidence: {ticket.confidence}")
print(f"✓ Escalated: {ticket.escalated}")
print(f"✓ Escalation reason: {ticket.escalation_reason}")


# --------------------------------------------------
# 2. Triage records
# --------------------------------------------------

print("\n===== TRIAGE RECORDS =====")
print(f"Count: {len(ticket.triage_records)}")

for triage in ticket.triage_records:
    print(
        f"✓ intent={triage.intent} | "
        f"confidence={triage.intent_confidence:.4f} | "
        f"sentiment={triage.sentiment} | "
        f"priority={triage.priority} | "
        f"department={triage.department}"
    )


# --------------------------------------------------
# 3. RAG logs
# --------------------------------------------------

print("\n===== RAG LOGS =====")
print(f"Count: {len(ticket.rag_logs)}")

for log in ticket.rag_logs:
    print(
        f"✓ query={log.query_text} | "
        f"top_similarity={log.top_similarity_score} | "
        f"retrieval_ms={log.retrieval_latency_ms} | "
        f"generation_ms={log.generation_latency_ms}"
    )


# --------------------------------------------------
# 4. Sources
# --------------------------------------------------

print("\n===== SOURCES =====")
print(f"Count: {len(ticket.sources)}")

for source in ticket.sources:
    print(
        f"✓ document={source.document} | "
        f"chunk={source.chunk_id} | "
        f"similarity={source.similarity:.4f}"
    )


# --------------------------------------------------
# 5. Final assertions
# --------------------------------------------------

assert ticket.id == ticket_id
assert len(ticket.triage_records) >= 1
assert len(ticket.rag_logs) >= 1

print("\n===== DATABASE INTEGRATION PASSED =====")
print("✓ Ticket persisted")
print("✓ Triage record persisted")
print("✓ RAG log persisted")
print("✓ Source records persisted")
print("✓ SupportService → Repository → SQLite integration works")
print("✅ CELL COMPLETED")

===== FINAL DATABASE PERSISTENCE VERIFICATION =====

Ticket ID: 8bec2ba0-c132-48fe-beaf-ea4813ee2139

===== TICKET =====
✓ Status: open
✓ Confidence: low
✓ Escalated: True
✓ Escalation reason: Intent confidence is below the configured threshold.

===== TRIAGE RECORDS =====
Count: 1
✓ intent=billing_and_payments | confidence=0.2263 | sentiment=negative | priority=high | department=billing

===== RAG LOGS =====
Count: 1
✓ query=I was charged $49.99 incorrectly and want a refund. | top_similarity=None | retrieval_ms=5303.56 | generation_ms=None

===== SOURCES =====
Count: 0

===== DATABASE INTEGRATION PASSED =====
✓ Ticket persisted
✓ Triage record persisted
✓ RAG log persisted
✓ Source records persisted
✓ SupportService → Repository → SQLite integration works
✅ CELL COMPLETED

In [62]:
print("===== TESTING SUCCESSFUL RAG SOURCE PERSISTENCE =====")

# Use a query that previously retrieved the FAQ knowledge base.
result_rag = service.chat(
    message="How can I reset my password?",
    conversation_id="db-rag-source-test-001",
)

print("\n===== CHAT RESULT =====")
print(f"Ticket ID: {result_rag.get('ticket_id')}")
print(f"Intent: {result_rag.get('intent')}")
print(f"Intent confidence: {result_rag.get('intent_confidence')}")
print(f"Confidence: {result_rag.get('confidence')}")
print(f"Escalated: {result_rag.get('escalate')}")

print("\nAnswer:")
print(result_rag.get("answer"))


# --------------------------------------------------
# Fetch persisted ticket
# --------------------------------------------------

ticket_id = result_rag.get("ticket_id")

if not ticket_id:
    raise RuntimeError("No ticket ID returned.")

ticket = repository.get_ticket_by_id(ticket_id)

if ticket is None:
    raise RuntimeError("Ticket was not persisted.")


# --------------------------------------------------
# Verify RAG sources
# --------------------------------------------------

print("\n===== PERSISTED RAG SOURCES =====")
print(f"Source count: {len(ticket.sources)}")

for source in ticket.sources:
    print(
        f"✓ document={source.document} | "
        f"page={source.page} | "
        f"chunk={source.chunk_id} | "
        f"similarity={source.similarity:.4f}"
    )


# --------------------------------------------------
# Verify RAG log
# --------------------------------------------------

print("\n===== PERSISTED RAG LOG =====")

print(f"RAG log count: {len(ticket.rag_logs)}")

for log in ticket.rag_logs:
    print(f"✓ Query: {log.query_text}")
    print(f"✓ Top similarity: {log.top_similarity_score}")
    print(f"✓ Retrieval latency: {log.retrieval_latency_ms} ms")
    print(f"✓ Generation latency: {log.generation_latency_ms} ms")


# --------------------------------------------------
# Final validation
# --------------------------------------------------

assert len(ticket.rag_logs) >= 1, \
    "RAG log was not persisted."

if result_rag.get("sources"):
    assert len(ticket.sources) >= 1, \
        "RAG returned sources but they were not persisted."

print("\n===== SUCCESSFUL RAG PERSISTENCE TEST PASSED =====")
print("✓ Ticket persisted")
print("✓ RAG log persisted")
print("✓ Retrieved sources were persisted when available")
print("✅ CELL COMPLETED")

===== TESTING SUCCESSFUL RAG SOURCE PERSISTENCE =====

===== CHAT RESULT =====
Ticket ID: 4cf99959-2f8a-4006-9a2d-880123a919a8
Intent: account_access
Intent confidence: 0.2843
Confidence: low
Escalated: True

Answer:
Based on the available support policy: [Source 1: faqs.jsonl; chunk faqs_jsonl_0004]

===== PERSISTED RAG SOURCES =====
Source count: 1
✓ document=faqs.jsonl | page=None | chunk=faqs_jsonl_0004 | similarity=0.7173

===== PERSISTED RAG LOG =====
RAG log count: 1
✓ Query: How can I reset my password?
✓ Top similarity: 0.7173
✓ Retrieval latency: 7.46 ms
✓ Generation latency: 0.0 ms

===== SUCCESSFUL RAG PERSISTENCE TEST PASSED =====
✓ Ticket persisted
✓ RAG log persisted
✓ Retrieved sources were persisted when available
✅ CELL COMPLETED

In [63]:
print("===== TESTING FASTAPI =====")

from fastapi.testclient import TestClient
from api.main import app

client = TestClient(app)


# --------------------------------------------------
# 1. Health endpoint
# --------------------------------------------------

print("\n===== GET /health =====")

response = client.get("/health")

print("Status:", response.status_code)
print("Response:", response.json())

assert response.status_code == 200
assert response.json().get("status") == "ok"

print("✓ Health endpoint passed")


# --------------------------------------------------
# 2. Analyze endpoint
# --------------------------------------------------

print("\n===== POST /analyze =====")

payload = {
    "message": "I was charged $49.99 incorrectly and want a refund."
}

response = client.post(
    "/analyze",
    json=payload
)

print("Status:", response.status_code)
print("Response:")

print(response.json())

assert response.status_code == 200

data = response.json()

required_fields = [
    "intent",
    "intent_confidence",
    "sentiment",
    "priority",
    "department",
]

missing = [
    field for field in required_fields
    if field not in data
]

if missing:
    raise RuntimeError(
        f"/analyze response is missing fields: {missing}"
    )

print("\n✓ Analyze endpoint passed")


# --------------------------------------------------
# Final result
# --------------------------------------------------

print("\n===== FASTAPI BASIC TEST PASSED =====")
print("✓ GET /health works")
print("✓ POST /analyze works")
print("✓ API returns the expected intelligence fields")
print("✅ CELL COMPLETED")

===== TESTING FASTAPI =====

===== GET /health =====
Status: 200
Response: {'status': 'ok', 'classifier_artifact': True, 'knowledge_index': True, 'llm_provider': 'mock'}
✓ Health endpoint passed

===== POST /analyze =====

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.bias   | UNEXPECTED |  |
roberta.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Status: 200
Response:
{'intent': 'billing_and_payments', 'intent_confidence': 0.2263, 'sentiment': 'negative', 'sentiment_confidence': 0.8662, 'entities': {'order_ids': [], 'amounts': ['$49.99'], 'dates': [], 'emails': []}, 'priority': 'high', 'department': 'billing', 'latency_ms': 2332.45}

✓ Analyze endpoint passed

===== FASTAPI BASIC TEST PASSED =====
✓ GET /health works
✓ POST /analyze works
✓ API returns the expected intelligence fields
✅ CELL COMPLETED

In [64]:
print("===== FINAL DATABASE CHECK =====")

from src.database.connection import get_engine

engine = get_engine()

print("Disposing all SQLAlchemy connections...")
engine.dispose()

print("✓ SQLAlchemy engine disposed")
print()
print("The remaining SQLite lock belongs to the current Colab")
print("Python kernel (PID 2347).")
print()
print("NEXT ACTION:")
print("Restart the Colab runtime/kernel.")

===== FINAL DATABASE CHECK =====
Disposing all SQLAlchemy connections...
✓ SQLAlchemy engine disposed

The remaining SQLite lock belongs to the current Colab
Python kernel (PID 2347).

NEXT ACTION:
Restart the Colab runtime/kernel.

In [ ]:
# Restarting the runtime
import os
os.kill(os.getpid(), 9)

In [1]:
# reconnecting to the database
import os
from pathlib import Path

PROJECT_ROOT = Path("/content/ai-customer-support-intelligence")
os.chdir(PROJECT_ROOT)

print("===== PROJECT RESTORED =====")
print("Working directory:", Path.cwd())
print("Project exists:", PROJECT_ROOT.exists())

from src.database.connection import get_engine, init_db

engine = get_engine()
init_db(engine)

print("\n===== DATABASE CHECK =====")
print("Database URL:", engine.url)

with engine.connect() as conn:
    result = conn.exec_driver_sql(
        "SELECT COUNT(*) FROM tickets"
    ).scalar()

print("Ticket count:", result)
print("✓ Database connection is working")
print("✅ CELL COMPLETED")

===== PROJECT RESTORED =====
Working directory: /content/ai-customer-support-intelligence
Project exists: True

===== DATABASE CHECK =====
Database URL: sqlite:///./artifacts/support_intelligence.db
Ticket count: 17
✓ Database connection is working
✅ CELL COMPLETED

In [2]:
#retest /chat
from fastapi.testclient import TestClient
from src.api.main import app

print("===== TESTING /CHAT AFTER RUNTIME RESTART =====")

with TestClient(app) as client:
    response = client.post(
        "/chat",
        json={
            "message": "How can I reset my password?",
            "conversation_id": "api-chat-test-002"
        }
    )

    print("\nStatus code:", response.status_code)
    print("\nResponse:")
    print(response.json())
    print("✅ CELL COMPLETED")

===== TESTING /CHAT AFTER RUNTIME RESTART =====

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Status code: 200

Response:
{'intent': 'account_access', 'intent_confidence': 0.2843, 'sentiment': 'neutral', 'sentiment_confidence': 0.8909, 'entities': {'order_ids': [], 'amounts': [], 'dates': [], 'emails': []}, 'priority': 'high', 'department': 'account_support', 'latency_ms': 14796.4, 'answer': 'Based on the available support policy: [Source 1: faqs.jsonl; chunk faqs_jsonl_0004]', 'sources': [{'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0004', 'similarity': 0.7173}], 'confidence': 'low', 'escalate': True, 'escalation_reason': 'Intent confidence is below the configured threshold.', 'conversation_id': 'api-chat-test-002', 'retrieval_latency_ms': 13450.65, 'generation_latency_ms': 0.01, 'analysis_latency_ms': 14796.4, 'total_latency_ms': 28279.12, 'ticket_id': '51ff9dc5-dd07-4b53-abff-0b825aa6a6c8'}
✅ CELL COMPLETED

In [3]:
from fastapi.testclient import TestClient
from src.api.main import app

print("===== SECOND /CHAT PERFORMANCE TEST =====")

with TestClient(app) as client:
    response = client.post(
        "/chat",
        json={
            "message": "How can I reset my password?",
            "conversation_id": "api-chat-test-003"
        }
    )

    data = response.json()

    print("Status code:", response.status_code)
    print("Latency:", data.get("latency_ms"), "ms")
    print("Retrieval latency:", data.get("retrieval_latency_ms"), "ms")
    print("Generation latency:", data.get("generation_latency_ms"), "ms")
    print("Ticket ID:", data.get("ticket_id"))
    print("✅ CELL COMPLETED")

===== SECOND /CHAT PERFORMANCE TEST =====
Status code: 200
Latency: 12.25 ms
Retrieval latency: 6.7 ms
Generation latency: 0.0 ms
Ticket ID: 3a6f20ab-d0f8-4062-b818-30d3b9bda34d
✅ CELL COMPLETED

In [4]:
# reloading files
import py_compile
from pathlib import Path

api_file = Path("src/api/main.py")

print("===== VERIFYING PATCH =====")

py_compile.compile(
    str(api_file),
    doraise=True
)

print("✓ src/api/main.py syntax is valid")

# Reload the module so the notebook uses the patched code.
import importlib
import src.api.main as api_main

api_main = importlib.reload(api_main)

print("✓ API module reloaded")
print("✓ Global service cache:", api_main._service)
print("✅ CELL COMPLETED")

===== VERIFYING PATCH =====
✓ src/api/main.py syntax is valid
✓ API module reloaded
✓ Global service cache: None
✅ CELL COMPLETED

In [5]:
# Measuring first request processing time and measures
from fastapi.testclient import TestClient
from src.api.main import app

print("===== FIRST REQUEST AFTER CACHING PATCH =====")

with TestClient(app) as client:
    response = client.post(
        "/chat",
        json={
            "message": "How can I reset my password?",
            "conversation_id": "api-performance-test-001"
        }
    )

    data = response.json()

    print("Status code:", response.status_code)
    print("Total latency:", data.get("latency_ms"), "ms")
    print("Retrieval latency:", data.get("retrieval_latency_ms"), "ms")
    print("Generation latency:", data.get("generation_latency_ms"), "ms")
    print("Intent:", data.get("intent"))
    print("Confidence:", data.get("confidence"))
    print("Sources:", data.get("sources"))
    print("Ticket ID:", data.get("ticket_id"))

print("\nCached service:", api._service if 'api' in globals() else "check src.api.main")

===== FIRST REQUEST AFTER CACHING PATCH =====

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Status code: 200
Total latency: 2318.54 ms
Retrieval latency: 5326.01 ms
Generation latency: 0.0 ms
Intent: account_access
Confidence: low
Sources: [{'document': 'faqs.jsonl', 'page': None, 'chunk_id': 'faqs_jsonl_0004', 'similarity': 0.7173}]
Ticket ID: 2a50b31d-6040-4602-9ad5-75abe2bd48d9

Cached service: check src.api.main

In [6]:
# checking whether caching service working or not
import time
import numpy as np

from src.api.main import _service

print("===== EMBEDDING vs FAISS BENCHMARK =====")

# Make sure the cached service exists.
if _service is None:
    raise RuntimeError("Cached service is not initialized. Run the /chat test first.")

retriever = _service.rag.retriever

# Ensure the FAISS index is loaded.
if retriever.store.index is None:
    retriever.store.load()

query = "How can I reset my password?"

# 1. Embedding only
start = time.perf_counter()
vector = retriever.embedder.encode_one(query).astype("float32").reshape(1, -1)
embedding_ms = (time.perf_counter() - start) * 1000

# 2. FAISS search only
import faiss

faiss.normalize_L2(vector)

start = time.perf_counter()
scores, indices = retriever.store.index.search(
    vector,
    min(3, retriever.store.index.ntotal)
)
faiss_ms = (time.perf_counter() - start) * 1000

print("Embedding time:", round(embedding_ms, 2), "ms")
print("FAISS search time:", round(faiss_ms, 4), "ms")
print("Vectors in index:", retriever.store.index.ntotal)
print("Embedding dimension:", vector.shape[1])

print("\nTop FAISS scores:")
print(scores[0])

===== EMBEDDING vs FAISS BENCHMARK =====
Embedding time: 11.43 ms
FAISS search time: 0.1665 ms
Vectors in index: 28
Embedding dimension: 384

Top FAISS scores:
[0.71729064 0.5057705  0.42566586]

In [7]:
# again testing  chat performance and time to process
import time
from fastapi.testclient import TestClient
from src.api.main import app

client = TestClient(app)

print("===== CACHED /CHAT PERFORMANCE =====")

payload = {
    "message": "How can I reset my password?"
}

# First request
start = time.perf_counter()
response1 = client.post("/chat", json=payload)
first_ms = (time.perf_counter() - start) * 1000

# Second request
start = time.perf_counter()
response2 = client.post("/chat", json=payload)
second_ms = (time.perf_counter() - start) * 1000

print("First request:", round(first_ms, 2), "ms")
print("Second request:", round(second_ms, 2), "ms")

print("\nReported analysis latency:")
print("First:", response1.json().get("latency_ms"), "ms")
print("Second:", response2.json().get("latency_ms"), "ms")

print("\nReported retrieval latency:")
print("First:", response1.json().get("retrieval_latency_ms"), "ms")
print("Second:", response2.json().get("retrieval_latency_ms"), "ms")

print("\nStatus:")
print(response1.status_code, response2.status_code)

===== CACHED /CHAT PERFORMANCE =====
First request: 29.35 ms
Second request: 26.08 ms

Reported analysis latency:
First: 13.18 ms
Second: 12.48 ms

Reported retrieval latency:
First: 7.35 ms
Second: 7.05 ms

Status:
200 200

In [8]:
# measuring time and measures  for same chat second time to check whether caching service is working
import importlib
import time
from fastapi.testclient import TestClient

import src.api.main as api

# Reload the modified source file.
api = importlib.reload(api)

client = TestClient(api.app)

response = client.post(
    "/chat",
    json={"message": "How can I reset my password?"}
)

print("===== /CHAT TIMING TEST =====")
print("Status:", response.status_code)

data = response.json()

print("\nLatency fields:")
print("analysis_latency_ms :", data.get("analysis_latency_ms"))
print("retrieval_latency_ms:", data.get("retrieval_latency_ms"))
print("generation_latency_ms:", data.get("generation_latency_ms"))
print("total_latency_ms    :", data.get("total_latency_ms"))

print("\nOld latency_ms present:", "latency_ms" in data)

print("\nTicket ID:", data.get("ticket_id"))
print("Confidence:", data.get("confidence"))
print("Escalate:", data.get("escalate"))

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

===== /CHAT TIMING TEST =====
Status: 200

Latency fields:
analysis_latency_ms : 2266.06
retrieval_latency_ms: 5228.19
generation_latency_ms: 0.0
total_latency_ms    : 7504.1

Old latency_ms present: True

Ticket ID: e124082e-70e3-47f5-a03a-f00c60e4a234
Confidence: low
Escalate: True

In [9]:
# measuring time and measures  for same chat second time to check whether caching service is working
import importlib
from fastapi.testclient import TestClient

import src.api.schemas as schemas
import src.api.main as api


importlib.reload(schemas)
api = importlib.reload(api)

client = TestClient(api.app)

response = client.post(
    "/chat",
    json={"message": "How can I reset my password?"}
)

print("===== FINAL /CHAT VALIDATION =====")
print("Status:", response.status_code)

if response.status_code == 200:
    data = response.json()

    print("\nLatency breakdown:")
    print("latency_ms            :", data.get("latency_ms"))
    print("analysis_latency_ms   :", data.get("analysis_latency_ms"))
    print("retrieval_latency_ms  :", data.get("retrieval_latency_ms"))
    print("generation_latency_ms :", data.get("generation_latency_ms"))
    print("total_latency_ms      :", data.get("total_latency_ms"))

    print("\nConsistency check:")
    print(
        "analysis == latency:",
        data.get("analysis_latency_ms") == data.get("latency_ms")
    )

    print("\nResponse:")
    print("Intent     :", data.get("intent"))
    print("Sentiment  :", data.get("sentiment"))
    print("Priority   :", data.get("priority"))
    print("Department :", data.get("department"))
    print("Confidence :", data.get("confidence"))
    print("Escalate   :", data.get("escalate"))
    print("Ticket ID  :", data.get("ticket_id"))

else:
    print("\nERROR:")
    print(response.text)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

===== FINAL /CHAT VALIDATION =====
Status: 200

Latency breakdown:
latency_ms            : 2380.56
analysis_latency_ms   : 2380.56
retrieval_latency_ms  : 5237.62
generation_latency_ms : 0.0
total_latency_ms      : 7629.13

Consistency check:
analysis == latency: True

Response:
Intent     : account_access
Sentiment  : neutral
Priority   : high
Department : account_support
Confidence : low
Escalate   : True
Ticket ID  : 811b0cca-46fd-4adc-a648-ae58c1c2cfcf

In [10]:
# Test API retrieval & intent endpoints
from fastapi.testclient import TestClient
import src.api.main as api

client = TestClient(api.app)

print("===== API ENDPOINT TEST =====")

# 1. Predict intent
intent_response = client.post(
    "/predict-intent",
    json={
        "message": "I forgot my password and cannot access my account."
    }
)

print("\n--- /predict-intent ---")
print("Status:", intent_response.status_code)
print("Response:", intent_response.json())


# 2. Retrieve knowledge
retrieve_response = client.post(
    "/retrieve",
    json={
        "message": "How can I reset my password?"
    }
)

print("\n--- /retrieve ---")
print("Status:", retrieve_response.status_code)

if retrieve_response.status_code == 200:
    data = retrieve_response.json()

    print("Query:", data.get("query"))
    print("Number of results:", len(data.get("results", [])))

    if data.get("results"):
        print("Top result:")
        print(data["results"][0])
else:
    print("Response:", retrieve_response.text)


# Final check
print("\n===== RESULT =====")

if (
    intent_response.status_code == 200
    and retrieve_response.status_code == 200
):
    print("✅ /predict-intent: PASS")
    print("✅ /retrieve: PASS")
else:
    print("❌ One or more endpoints failed.")

===== API ENDPOINT TEST =====

--- /predict-intent ---
Status: 200
Response: {'intent': 'account_access', 'confidence': 0.3536591718030705}

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

--- /retrieve ---
Status: 200
Query: How can I reset my password?
Number of results: 1
Top result:
{'chunk_id': 'faqs_jsonl_0004', 'text': "Question: How do I reset my account password if I forgot it? Answer: Click 'Forgot Password' on the login screen, enter your registered email, and a secure password reset link valid for 15 minutes will be emailed to you.", 'document': 'faqs.jsonl', 'page': None, 'section': None, 'similarity': 0.7173}

===== RESULT =====
✅ /predict-intent: PASS
✅ /retrieve: PASS

In [11]:
# Test Cell 2 — Knowledge ingestion & index refresh
from fastapi.testclient import TestClient
from pathlib import Path
import src.api.main as api

client = TestClient(api.app)

print("===== KNOWLEDGE INGESTION API TEST =====")

response = client.post("/knowledge/ingest")

print("Status:", response.status_code)
print("Response:", response.json())

print("\n===== INDEX FILES AFTER INGESTION =====")

index_path = Path(
    "/content/ai-customer-support-intelligence/models/embeddings/faiss.index"
)

metadata_path = Path(
    "/content/ai-customer-support-intelligence/models/embeddings/metadata.json"
)

print("FAISS index exists:", index_path.exists())
print("Metadata exists:", metadata_path.exists())

if index_path.exists():
    print("FAISS index size:", index_path.stat().st_size, "bytes")

if metadata_path.exists():
    print("Metadata size:", metadata_path.stat().st_size, "bytes")

print("\n===== RESULT =====")

if (
    response.status_code == 200
    and index_path.exists()
    and metadata_path.exists()
):
    print("✅ /knowledge/ingest: PASS")
    print("✅ Persistent knowledge index: PASS")
else:
    print("❌ Knowledge ingestion test failed.")

===== KNOWLEDGE INGESTION API TEST =====

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Indexed 28 chunks from 28 source records.
Status: 200
Response: {'status': 'ok', 'message': 'Knowledge index rebuilt.'}

===== INDEX FILES AFTER INGESTION =====
FAISS index exists: True
Metadata exists: True
FAISS index size: 43053 bytes
Metadata size: 14427 bytes

===== RESULT =====
✅ /knowledge/ingest: PASS
✅ Persistent knowledge index: PASS

In [12]:
# Test Cell 3 — Ticket API & SQLite persistence
from fastapi.testclient import TestClient
import src.api.main as api

client = TestClient(api.app)

print("===== TICKET API TEST =====")

# 1. Create a fresh ticket through /chat
chat_response = client.post(
    "/chat",
    json={
        "message": "I forgot my password and need help accessing my account."
    }
)

print("\n--- Create ticket via /chat ---")
print("Status:", chat_response.status_code)

if chat_response.status_code != 200:
    print("Response:", chat_response.text)
else:
    chat_data = chat_response.json()
    ticket_id = chat_data.get("ticket_id")

    print("Ticket ID:", ticket_id)

    # 2. List tickets
    tickets_response = client.get("/tickets")

    print("\n--- GET /tickets ---")
    print("Status:", tickets_response.status_code)

    if tickets_response.status_code == 200:
        tickets_data = tickets_response.json()
        print("Response type:", type(tickets_data).__name__)
        print("Tickets returned:", len(tickets_data))
    else:
        print("Response:", tickets_response.text)

    # 3. Retrieve the specific ticket
    ticket_response = client.get(
        f"/tickets/{ticket_id}"
    )

    print("\n--- GET /tickets/{ticket_id} ---")
    print("Status:", ticket_response.status_code)

    if ticket_response.status_code == 200:
        ticket_data = ticket_response.json()
        print("Retrieved ticket ID:", ticket_data.get("id"))
        print("Intent:", ticket_data.get("intent"))
        print("Priority:", ticket_data.get("priority"))
    else:
        print("Response:", ticket_response.text)

    # Final checks
    print("\n===== RESULT =====")

    passed = (
        chat_response.status_code == 200
        and bool(ticket_id)
        and tickets_response.status_code == 200
        and ticket_response.status_code == 200
        and ticket_data.get("id") == ticket_id
    )

    if passed:
        print("✅ /chat ticket creation: PASS")
        print("✅ GET /tickets: PASS")
        print("✅ GET /tickets/{ticket_id}: PASS")
        print("✅ SQLite ticket persistence: PASS")
    else:
        print("❌ Ticket persistence/API test failed.")

===== TICKET API TEST =====

--- Create ticket via /chat ---
Status: 200
Ticket ID: 95e6cbfb-5192-4f4e-b2fc-cc0cc13ae3fa

--- GET /tickets ---
Status: 200
Response type: list
Tickets returned: 25

--- GET /tickets/{ticket_id} ---
Status: 200
Retrieved ticket ID: 95e6cbfb-5192-4f4e-b2fc-cc0cc13ae3fa
Intent: None
Priority: None

===== RESULT =====
✅ /chat ticket creation: PASS
✅ GET /tickets: PASS
✅ GET /tickets/{ticket_id}: PASS
✅ SQLite ticket persistence: PASS

In [13]:
# Test Cell 4 — End-to-end scenarios
from fastapi.testclient import TestClient
import src.api.main as api

client = TestClient(api.app)

scenarios = [
    ("Normal support", "How can I reset my password?"),
    ("Negative customer", "I was charged twice for the same payment and this is very frustrating."),
    ("Irrelevant question", "What is the weather like on Mars?"),
    ("Security issue", "Someone accessed my account and I cannot log in.")
]

print("===== END-TO-END SCENARIO TEST =====")

passed = 0

for name, message in scenarios:
    response = client.post(
        "/chat",
        json={"message": message}
    )

    print(f"\n--- {name} ---")
    print("Status:", response.status_code)

    if response.status_code == 200:
        data = response.json()

        print("Intent     :", data.get("intent"))
        print("Sentiment  :", data.get("sentiment"))
        print("Priority   :", data.get("priority"))
        print("Department :", data.get("department"))
        print("Confidence :", data.get("confidence"))
        print("Escalate   :", data.get("escalate"))
        print("Sources    :", len(data.get("sources", [])))
        print("Ticket ID  :", data.get("ticket_id"))

        passed += 1
    else:
        print("ERROR:", response.text)

print("\n===== RESULT =====")
print(f"Scenarios passed: {passed}/{len(scenarios)}")

if passed == len(scenarios):
    print("✅ End-to-end scenario test: PASS")
else:
    print("❌ Some end-to-end scenarios failed.")

===== END-TO-END SCENARIO TEST =====

--- Normal support ---
Status: 200
Intent     : account_access
Sentiment  : neutral
Priority   : high
Department : account_support
Confidence : low
Escalate   : True
Sources    : 1
Ticket ID  : 851674d5-b15b-4a5c-9eed-3b51e3be42d4

--- Negative customer ---
Status: 200
Intent     : billing_and_payments
Sentiment  : negative
Priority   : high
Department : billing
Confidence : low
Escalate   : True
Sources    : 1
Ticket ID  : e2deb46f-29ad-461f-afaa-990fd8ffa554

--- Irrelevant question ---
Status: 200
Intent     : general_inquiry
Sentiment  : neutral
Priority   : medium
Department : customer_support
Confidence : low
Escalate   : True
Sources    : 0
Ticket ID  : 04acc49f-9e73-40f8-a5d8-48ab422418d3

--- Security issue ---
Status: 200
Intent     : account_access
Sentiment  : negative
Priority   : high
Department : account_support
Confidence : low
Escalate   : True
Sources    : 0
Ticket ID  : 60351778-3f05-4302-a8d8-eb3e6a3bee40

===== RESULT =====
Scenarios passed: 4/4
✅ End-to-end scenario test: PASS

In [14]:
# Final Test Cell — 5 Now run the project's actual automated test suite:
import subprocess
import sys

project_root = "/content/ai-customer-support-intelligence"

print("===== FINAL PROJECT TEST SUITE =====")

result = subprocess.run(
    [sys.executable, "-m", "pytest", "-q"],
    cwd=project_root,
    capture_output=True,
    text=True
)

print(result.stdout)

if result.stderr:
    print("\n===== STDERR =====")
    print(result.stderr)

print("\n===== FINAL RESULT =====")

if result.returncode == 0:
    print("✅ ALL AUTOMATED TESTS PASSED")
else:
    print("❌ SOME AUTOMATED TESTS FAILED")
    print("Exit code:", result.returncode)

===== FINAL PROJECT TEST SUITE =====
...........                                                              [100%]
11 passed in 0.56s


===== FINAL RESULT =====
✅ ALL AUTOMATED TESTS PASSED

# streamlit dashboard running

In [15]:
# 1. Install Cloudflared CLI
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

Selecting previously unselected package cloudflared.
(Reading database ... 126952 files and directories currently installed.)
Preparing to unpack cloudflared-linux-amd64.deb ...
Unpacking cloudflared (2026.9.3) ...
Setting up cloudflared (2026.9.3) ...
Processing triggers for man-db (2.12.0-4build2) ...

In [16]:

# 1. Install Streamlit
!pip install -q streamlit

# 2. Go to project root
%cd "/content/ai-customer-support-intelligence"

# 3. Start Streamlit in the background
!streamlit run dashboard/app.py --server.address 0.0.0.0 --server.port 8501 > streamlit.log 2>&1 &

# 4. Give Streamlit a few seconds to start
import time
time.sleep(5)

# 5. Check Streamlit log
!cat streamlit.log

# 6. Start Cloudflare Tunnel
!cloudflared tunnel --url http://127.0.0.1:8501

/content

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-09-29 03:52:01.554 Uvicorn server started on 0.0.0.0:8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://136.85.93.66:8501

2026-09-29T03:52:05Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-09-29T03:52:05Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-09-29T03:52:10Z INF +--------------------------------------------------------------------------------------------+
2026-09-29T03:52:10Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-09-29T03:52:10Z INF |  https://nickel-promising-plus-efficiently.trycloudflare.com                               |
2026-09-29T03:52:10Z INF +--------------------------------------------------------------------------------------------+
2026-09-29T03:52:10Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-09-29T03:52:10Z INF Version 2026.9.3 (Checksum 77e26d8d900e0b8469f416239d14b5f296525fdf79fee6f511ef55609e3fbac2)
2026-09-29T03:52:10Z INF GOOS: linux, GOVersion: go1.26.8, GoArch: amd64
2026-09-29T03:52:10Z INF Settings: map[ha-connections:1 protocol:quic url:http://127.0.0.1:8501]
2026-09-29T03:52:10Z INF cloudflared will not automatically update if installed by a package manager.
2026-09-29T03:52:10Z INF Generated Connector ID: 9d5a88b5-7555-4b34-a7cb-34693eb9ece0
2026-09-29T03:52:10Z INF Initial protocol quic
2026-09-29T03:52:10Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-09-29T03:52:10Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026/09/29 03:52:10 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-09-29T03:52:10Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-09-29T03:52:10Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-09-29T03:52:10Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-09-29T03:52:10Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.192.77
2026-09-29T03:52:10Z INF Registered tunnel connection connIndex=0 connection=4da78798-d5e5-4185-b576-d647744e02f2 event=0 ip=198.41.192.77 location=sin16 protocol=quic
2026-09-29T03:52:16Z INF +-------------------------------------------------------------------------------------+
2026-09-29T03:52:16Z INF |                               CONNECTIVITY PRE-CHECKS                               |
2026-09-29T03:52:16Z INF +-------------------------------------------------------------------------------------+
2026-09-29T03:52:16Z INF |  COMPONENT         TARGET                     STATUS  DETAILS                       |
2026-09-29T03:52:16Z INF |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-09-29T03:52:16Z INF |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-09-29T03:52:16Z INF |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-09-29T03:52:16Z INF |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-09-29T03:52:16Z INF |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-09-29T03:52:16Z INF |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-09-29T03:52:16Z INF |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |
2026-09-29T03:52:16Z INF |                                                                                     |
2026-09-29T03:52:16Z INF |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |
2026-09-29T03:52:16Z INF +-------------------------------------------------------------------------------------+
2026-09-29T03:52:16Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=2bab48b3-fcf3-4213-a71d-c8ccea0f4bc8 status=pass target=region1.v2.argotunnel.com
2026-09-29T03:52:16Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=2bab48b3-fcf3-4213-a71d-c8ccea0f4bc8 status=pass target=region2.v2.argotunnel.com
2026-09-29T03:52:16Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=2bab48b3-fcf3-4213-a71d-c8ccea0f4bc8 status=pass target=region1.v2.argotunnel.com
2026-09-29T03:52:16Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=2bab48b3-fcf3-4213-a71d-c8ccea0f4bc8 status=pass target=region2.v2.argotunnel.com
2026-09-29T03:52:16Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=2bab48b3-fcf3-4213-a71d-c8ccea0f4bc8 status=pass target=region1.v2.argotunnel.com
2026-09-29T03:52:16Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=2bab48b3-fcf3-4213-a71d-c8ccea0f4bc8 status=pass target=region2.v2.argotunnel.com
2026-09-29T03:52:16Z INF precheck component="Cloudflare API" details="API is reachable" run_id=2bab48b3-fcf3-4213-a71d-c8ccea0f4bc8 status=pass target=api.cloudflare.com:443
2026-09-29T03:52:16Z INF precheck complete hard_fail=false run_id=2bab48b3-fcf3-4213-a71d-c8ccea0f4bc8 suggested_protocol=quic
2026-09-29T03:52:22Z INF Initiating graceful shutdown due to signal interrupt ...
2026-09-29T03:52:22Z INF Retrying connection in up to 2s connIndex=0 event=0 ip=198.41.192.77
2026-09-29T03:52:22Z ERR Connection terminated connIndex=0
2026-09-29T03:52:22Z ERR no more connections active and exiting
2026-09-29T03:52:22Z INF Tunnel server stopped
2026-09-29T03:52:22Z INF Metrics server stopped